#pragma once

#ifndef __DPCINIT_H
#define __DPCINIT_H

EXTERN void LGAPI CreateDeepCover(void);
DEFINE_LG_GUID(UUID_DEEPC, 0x348);

//
// KEEP THIS FILE RELATIVELY CLEAR OF JUNK!  DO NOT PUT YOUR SYSTEM'S API HERE! 
// DO NOT INCLUDE OTHER HEADER FILES FROM THIS FILE!
//

#endif // __DPCINIT_H

