; Debug header file x:\prj\tech\h/_dstruct.__i made from libdbg.dbg by DBGMAKEH

DB_DSTRUCT equ 6
DS_DSTRUCT_General equ 01h
DSRC_DSTRUCT_General equ 030000001h
DS_DSTRUCT_Hash equ 02h
DSRC_DSTRUCT_Hash equ 030000002h
DS_DSTRUCT_Msg equ 04h
DSRC_DSTRUCT_Msg equ 030000004h
DS_DSTRUCT_MsgList equ 08h
DSRC_DSTRUCT_MsgList equ 030000008h
DS_DSTRUCT_MsgTable equ 010h
DSRC_DSTRUCT_MsgTable equ 030000010h
