; Debug header file x:\prj\tech\h/_res.__i made from libdbg.dbg by DBGMAKEH

DB_RES equ 5
DS_RES_General equ 01h
DSRC_RES_General equ 028000001h
DS_RES_ChkIdRef equ 02h
DSRC_RES_ChkIdRef equ 028000002h
DS_RES_ChkLock equ 04h
DSRC_RES_ChkLock equ 028000004h
DS_RES_Make equ 08h
DSRC_RES_Make equ 028000008h
DS_RES_Read equ 010h
DSRC_RES_Read equ 028000010h
DS_RES_Write equ 020h
DSRC_RES_Write equ 028000020h
DS_RES_DelDrop equ 040h
DSRC_RES_DelDrop equ 028000040h
DS_RES_Stat equ 080h
DSRC_RES_Stat equ 028000080h
DS_RES_CumStat equ 0100h
DSRC_RES_CumStat equ 028000100h
DS_RES_LockAll equ 0200h
DSRC_RES_LockAll equ 028000200h
DS_RES_FileInfo equ 0400h
DSRC_RES_FileInfo equ 028000400h
