;
; $Source: r:/prj/lib/src/timer/rcs/tmrec.inc $
; $Revision: 1.1 $
; $Author
; $Date: 1993/05/20 15:50:29 $
;
; Format of timer record.
;
; This file is part of the timer library.
;
; $Log: tmrec.inc $
; Revision 1.1  1993/05/20  15:50:29  kaboom
; Initial revision
; 

TMR_STATUS      equ 0
TMR_COUNT       equ 4
TMR_DENOM       equ 8
TMR_REAL_FUNC   equ 12
TMR_PROT_FUNC   equ 16
TMR_SIZE        equ 20
