;
; $Source: r:/prj/lib/src/timer/rcs/tmreg.inc $
; $Revision: 1.1 $
; $Author
; $Date: 1993/05/20 15:50:46 $
;
; Timer port/mode definitions.
;
; This file is part of the timer library.
;
; $Log: tmreg.inc $
; Revision 1.1  1993/05/20  15:50:46  kaboom
; Initial revision
; 

TMD_INT         equ 8
TMD_FREQ        equ 1193180
TMD_DEF_DENOM   equ 10000h
TMP_MODE        equ 43h
TMP_CHAN0       equ 40h
TMM_RATEGEN     equ 34h
TMM_SQUARE      equ 36h
