; $Header: x:/prj/tech/libsrc/g2/RCS/g2spoint.inc 1.1 1998/04/28 14:32:37 KEVIN Exp $
;
; mirror g2spoint.h

ifndef g2spoint_inc
g2spoint_inc equ 1

G2S_POINT_SX            equ 0t
G2S_POINT_SY            equ 4t
G2S_POINT_W             equ 8t
G2S_POINT_FLAGS         equ 12t
G2S_POINT_I             equ 16t
G2S_POINT_U             equ 20t
G2S_POINT_V             equ 24t
G2S_POINT_H             equ 28t
G2S_POINT_D             equ 32t
G2S_POINT_COORD         equ 16t

endif
