;
; $Source: s:/prj/tech/libsrc/g2/RCS/plytyp.inc $
; $Revision: 1.2 $
; $Author: KEVIN $
; $Date: 1996/04/11 09:38:11 $
;
; Public polygon-related data structures.
;
; This file is part of the g2 library.
;

ifndef plytyp_inc
plytyp_inc equ 1

GRS_VERTEX_X            equ     0
GRS_VERTEX_Y            equ     4
GRS_VERTEX_U            equ     8
GRS_VERTEX_V            equ     12
GRS_VERTEX_W            equ     16
GRS_VERTEX_I            equ     20

endif   ;ndef plytyp_inc
