; $Header: x:/prj/tech/libsrc/dev2d/RCS/gdican.inc 1.1 1996/08/22 15:12:35 KEVIN Exp $
; Canvas function table indexes.

ifndef gdican_inc
gdican_inc equ 1

GDC_UPIX                equ     0t 
GDC_UPIX_EXPOSE         equ     1t
GDC_UPIX8               equ     2t
GDC_UPIX8_EXPOSE        equ     3t
GDC_UPIX16              equ     4t 
GDC_UPIX16_EXPOSE       equ     5t
GDC_UPIX24              equ     6t
GDC_UPIX24_EXPOSE       equ     7t
GDC_LPIX                equ     8t 
GDC_LPIX_EXPOSE         equ     9t
GDC_LPIX8               equ     10t
GDC_LPIX8_EXPOSE        equ     11t
GDC_LPIX16              equ     12t
GDC_LPIX16_EXPOSE       equ     13t
GDC_LPIX24              equ     14t
GDC_LPIX24_EXPOSE       equ     15t
GDC_UGPIX8              equ     16t
GDC_UGPIX8_EXPOSE       equ     17t
GDC_UGPIX16             equ     18t
GDC_UGPIX16_EXPOSE      equ     19t
GDC_UGPIX24             equ     20t
GDC_UGPIX24_EXPOSE      equ     21t
GDC_UBITMAP             equ     22t
GDC_UBITMAP_EXPOSE      equ     23t
GDC_UHLINE              equ     24t
GDC_UHLINE_EXPOSE       equ     25t
GDC_UVLINE              equ     26t
GDC_UVLINE_EXPOSE       equ     27t
GDC_CANVAS_FUNCS        equ     28t

endif
