; $Header: x:/prj/tech/libsrc/r3d/RCS/ctxts.inc 1.1 1996/10/29 12:45:22 KEVIN Exp $

ifndef ctxts_inc
ctxts_inc equ 1

; r3s_global_context descriptor
R3S_GLOBAL_CONTEXT_X_PRJ        equ 00t
R3S_GLOBAL_CONTEXT_Y_PRJ        equ 04t
R3S_GLOBAL_CONTEXT_X_CLIP       equ 08t
R3S_GLOBAL_CONTEXT_Y_CLIP       equ 12t
R3S_GLOBAL_CONTEXT_X_OFF        equ 16t
R3S_GLOBAL_CONTEXT_Y_OFF        equ 20t
R3S_GLOBAL_CONTEXT_CUR_STRIDE   equ 24t

endif
