call append CAMGUIDS.C
call append CHATIID.H
call append CHEVKIND.H
call append version.c
call append VERSION.H
call append VHOT.H
call append VISMSG.H
call append _ANIMTXT.H
call append _EDITGEO.H
call append oldasfx.c
call append FINDHACK.H
call append FREZREAC.H
call append GENTABLE.C
call append GIDPROP.H
call append GLOBALID.H
call append GOOF.C
call append GSTRGUID.H
call append GTOOLIID.H
call append INC.C
call append INCLEX.C
call append INCTAB.H
call append INCTOK.H
call append KEYCMD.C
call append KEYCMD.H
call append MISCDBG.H
call append pch.h
call append DARKTABL.C
call append SONGYACC.C
call append DIALOGS.H
call append NANODEF.H
call append PACKETS.H
call append PERSLOOP.H
call append REG.H
call append SAMPAPP.H
call append SAMPLOOP.H
call append SAMPPROP.H
call append SONGTOK.H
call append TESTLOOP.C
call append TESTMODE.C
call append TESTLOOP.H
call append TESTMODE.H
call append RENDER\ANIMLGT.C
call append RENDER\ANIMLGT.H
call append RENDER\ANIMLGTE.H
call append RENDER\ANIMLGTS.H
call append RENDER\ANIMLGTT.H
call append RENDER\ANIMTEXT.H
call append RENDER\ANIM_TXT.C
call append RENDER\ANIM_TXT.H
call append RENDER\ANTXLOOP.H
call append RENDER\WEATHERG.H
call append RENDER\ANTXSCPT.H
call append RENDER\ANTXTYPE.H
call append RENDER\BSPPINFO.H
call append RENDER\CAMERA.H
call append RENDER\CAMOVL.H
call append RENDER\CELSTOBJ.H
call append RENDER\CLOUDOBJ.H
call append RENDER\CORONAG.H
call append RENDER\CTIMER.H
call append RENDER\TEXMEM.H
call append RENDER\TEXPROP.C
call append RENDER\TEXPROP.H
call append RENDER\TEXSAVE.H
call append RENDER\TEXTARCH.H
call append RENDER\TEXTRGFH.H
call append RENDER\TEXTURE.H
call append RENDER\WEATHER.H
call append RENDER\SPRKS.H
call append RENDER\SPRKT.H
call append RENDER\STARHACK.C
call append RENDER\RENDOBJ.H
call append RENDER\STARHACK.H
call append RENDER\STAROBJ.H
call append RENDER\TANIMIID.H
call append RENDER\TANIMPRP.H
call append RENDER\rendloop.c
call append RENDER\SKYOBJ.H
call append RENDER\SKYREND.H
call append RENDER\SLITPROP.H
call append RENDER\SPHRCST.H
call append RENDER\SPHRCSTS.H
call append RENDER\SPHRCSTT.H
call append RENDER\SPRKPROP.H
call append RENDER\SCRNLOOP.C
call append RENDER\SCRNLOOP.H
call append RENDER\SCRNMAN.C
call append RENDER\SCRNMAN.H
call append RENDER\SCRNMODE.H
call append RENDER\SCRNOVLS.H
call append RENDER\SCRNSTR.H
call append RENDER\SKYINT.H
call append RENDER\RENDPROP.H
call append RENDER\RENDPTST.C
call append RENDER\RENDPTST.H
call append RENDER\RNDFLASH.H
call append RENDER\ROBJBASE.H
call append RENDER\ROBJTYPE.H
call append RENDER\SCALPROP.H
call append RENDER\SCRNGUID.H
call append RENDER\PORTHLPR.C
call append RENDER\PORTHLPR.H
call append RENDER\RENDER.H
call append RENDER\RENDLOOP.H
call append RENDER\palmgr.c
call append RENDER\RENDPHYS.H
call append RENDER\PARTICLE.H
call append RENDER\PARTPROP.H
call append RENDER\PARTTYPE.H
call append RENDER\PGROUP.C
call append RENDER\PGROUP.H
call append RENDER\PGRPPROP.H
call append RENDER\PORTAPP.C
call append RENDER\PORTAPP.H
call append RENDER\OBJSHAPE.H
call append RENDER\OBJSLIT.H
call append RENDER\OBJTXTRP.H
call append RENDER\PALETTE.C
call append RENDER\family.c
call append RENDER\PALETTE.H
call append RENDER\PALMGR.H
call append RENDER\PARTGRP.H
call append RENDER\MNAMPROP.H
call append RENDER\MNUMPROP.H
call append RENDER\OBJCAST.H
call append RENDER\OBJSCALE.H
call append RENDER\OBJLIGHT.C
call append RENDER\OBJLIGHT.H
call append RENDER\OBJMODEL.C
call append RENDER\OBJMODEL.H
call append RENDER\MESHRAY.H
call append RENDER\MESHTEX.H
call append RENDER\MESHTEXG.H
call append RENDER\MESHTYPE.H
call append RENDER\MIPMAP.C
call append RENDER\MIPMAP.H
call append RENDER\MISSREND.H
call append RENDER\MLIGHT.C
call append RENDER\MLIGHT.H
call append RENDER\LITPROPS.H
call append RENDER\LITPROPT.H
call append RENDER\MEDMOTN.C
call append RENDER\MEDMOTN.H
call append RENDER\MEDMOTNS.H
call append RENDER\MEDMOTNT.H
call append RENDER\MESHATT.H
call append RENDER\MESHATTS.H
call append RENDER\MESHRAY.C
call append RENDER\HDSKBASE.H
call append RENDER\HDSKPROP.H
call append RENDER\HUD.C
call append RENDER\HUD.H
call append RENDER\LIGHT.H
call append RENDER\LITDBG.H
call append RENDER\LITNET.H
call append RENDER\LITPROP.H
call append RENDER\FXSPAN.H
call append RENDER\FXSPANS.H
call append RENDER\FXSPANT.H
call append RENDER\GAMMA.H
call append RENDER\GFXPROP.H
call append RENDER\H2OCOLID.H
call append RENDER\H2OCOLOR.H
call append RENDER\CTRAST.C
call append RENDER\texmem.c
call append RENDER\FAMILY.H
call append RENDER\FAMILY_.H
call append RENDER\FAS.C
call append RENDER\FAS.H
call append RENDER\FASPROP.H
call append RENDER\FASTYPE.H
call append RENDER\FXDISK.C
call append RENDER\FXDISK.H
call append RENDER\FXSPAN.C
call append RENDER\DISTOBJ.H
call append RENDER\DYNIID.H
call append RENDER\DYNTEX.H
call append RENDER\ELITPROP.H
call append RENDER\FACE.H
call append RENDER\FACEG.H
call append RENDER\DISPLOOP.H
call append RENDER\CORONA.H
call append RENDER\CTIMER.C
call append RENDER\CTRAST.H
call append RENDER\CAMERA.C
call append SCRIPT\ARSCRM.H
call append SCRIPT\ARSCRP.H
call append SCRIPT\ARSCRS.H
call append SCRIPT\ARSCRT.H
call append SCRIPT\ATKSCRPT.H
call append SCRIPT\BODSCRPT.H
call append SCRIPT\SCRPTPRP.H
call append SCRIPT\SCRPTPR_.H
call append SCRIPT\SCRPTST.H
call append SCRIPT\SIMSCRM.H
call append SCRIPT\SNDSCRPT.H
call append SCRIPT\SNDSCRP_.H
call append SCRIPT\TWQSCRPT.H
call append SCRIPT\CDSCRIPT.H
call append SCRIPT\PUPSCRPT.H
call append SCRIPT\QUESSCPT.H
call append SCRIPT\REPSCRPT.H
call append SCRIPT\ROOSCRPT.H
call append SCRIPT\SCRPTCMD.H
call append SCRIPT\SCRPTNE_.H
call append SCRIPT\NETSCRPT.H
call append SCRIPT\OBJSCRM.H
call append SCRIPT\OBJSCRPT.H
call append SCRIPT\OBJSCRT.H
call append SCRIPT\PGRPSCPT.H
call append SCRIPT\KEYSCPT.H
call append SCRIPT\LINKSCPT.H
call append SCRIPT\LITSCRPT.H
call append SCRIPT\LOCKSCPT.H
call append SCRIPT\MISCRPRT.H
call append SCRIPT\MTSCRPT.H
call append SCRIPT\DATASCRS.H
call append SCRIPT\DRSCRPT.H
call append SCRIPT\ENGSCRPT.H
call append SCRIPT\FROBSCRM.H
call append SCRIPT\FROBSCRP.H
call append SCRIPT\FROBSCRT.H
call append SCRIPT\CAMSCRS.H
call append SCRIPT\CONTSCPT.H
call append SCRIPT\CONTSCRM.H
call append SCRIPT\CONTSCRS.H
call append SCRIPT\DAMGSCRM.H
call append SCRIPT\DAMGSCRP.H
call append SCRIPT\DAMGSCRS.H
call append SHOCK\SHKABYSS.H
call append SHOCK\SHKAI.H
call append SHOCK\SHKAIABS.H
call append SHOCK\SHKAIBIT.H
call append SHOCK\SHKYORN.H
call append SHOCK\SHK_BIND.H
call append SHOCK\TRANSMID.H
call append SHOCK\TRANSMOD.H
call append SHOCK\SHKAICBR.H
call append SHOCK\SHKAIGRB.H
call append SHOCK\SHKAIHCK.H
call append SHOCK\SHKAIPRB.H
call append SHOCK\SHKVHOT.H
call append SHOCK\SHKWEB.H
call append SHOCK\SHKWEPSC.H
call append SHOCK\SHKWSETT.H
call append SHOCK\SHKWSPRP.H
call append SHOCK\SHKTRIP.H
call append SHOCK\SHKTRPSI.H
call append SHOCK\SHKTYPES.H
call append SHOCK\SHKUITUL.H
call append SHOCK\SHKUTILS.H
call append SHOCK\SHKVER.H
call append SHOCK\SHKTECH.H
call append SHOCK\SHKTECHS.H
call append SHOCK\SHKTLUCT.H
call append SHOCK\SHKTRAIN.H
call append SHOCK\SHKTRAIT.H
call append SHOCK\SHKTRCST.H
call append SHOCK\SHKSTNRC.H
call append SHOCK\SHKSVBND.H
call append SHOCK\SHKSWMPR.H
call append SHOCK\SHKTABLE.C
call append SHOCK\SHKTCOMP.H
call append SHOCK\SHKSNDPR.H
call append SHOCK\SHKSOUND.H
call append SHOCK\SHKSPAWN.H
call append SHOCK\SHKSPFLG.H
call append SHOCK\SHKSTACK.H
call append SHOCK\SHKSTATS.H
call append SHOCK\SHKSTCST.H
call append SHOCK\SHKSCOMP.H
call append SHOCK\SHKSCRM.H
call append SHOCK\SHKSCRPT.H
call append SHOCK\SHKSECUR.H
call append SHOCK\SHKSKILL.H
call append SHOCK\SHKRNDOV.H
call append SHOCK\SHKRNDST.H
call append SHOCK\SHKRSPRP.H
call append SHOCK\SHKRSRCH.H
call append SHOCK\SHKSAVUI.H
call append SHOCK\SHKSCAPI.H
call append SHOCK\SHKREACT.H
call append SHOCK\SHKREND.C
call append SHOCK\SHKREND.H
call append SHOCK\SHKREP.H
call append SHOCK\SHKREPRT.H
call append SHOCK\SHKRLUP2.H
call append SHOCK\SHKRLUP2.C
call append SHOCK\SHKPSIPW.H
call append SHOCK\SHKPSISC.H
call append SHOCK\SHKPSITY.H
call append SHOCK\SHKQBIND.H
call append SHOCK\SHKRADAR.H
call append SHOCK\SHKRDRBS.H
call append SHOCK\SHKRDROV.H
call append SHOCK\SHKPSAMP.H
call append SHOCK\SHKPSAPI.H
call append SHOCK\SHKPSI.H
call append SHOCK\SHKPSIBS.H
call append SHOCK\SHKPSIIF.H
call append SHOCK\SHKPSIPR.H
call append SHOCK\SHKPLPUP.H
call append SHOCK\SHKPLTYP.H
call append SHOCK\SHKPRJPR.H
call append SHOCK\SHKPROJ.H
call append SHOCK\SHKPROP.H
call append SHOCK\SHKPRUTL.H
call append SHOCK\SHKPLAYR.H
call append SHOCK\SHKPLCST.H
call append SHOCK\SHKPLDMG.H
call append SHOCK\SHKPLGUN.H
call append SHOCK\SHKPLIID.H
call append SHOCK\SHKPLPRP.H
call append SHOCK\SHKPLPSI.H
call append SHOCK\SHKPDA.H
call append SHOCK\SHKPDCST.H
call append SHOCK\SHKPDOLL.H
call append SHOCK\SHKPFIID.H
call append SHOCK\SHKPGAPI.H
call append SHOCK\SHKPICK.H
call append SHOCK\SHKPJBAS.H
call append SHOCK\SHKOVCST.H
call append SHOCK\SHKOVRLD.H
call append SHOCK\SHKOVRLY.H
call append SHOCK\SHKPARAM.H
call append SHOCK\SHKPATCH.H
call append SHOCK\SHKNET.H
call append SHOCK\SHKNETAP.H
call append SHOCK\SHKNETID.H
call append SHOCK\SHKNETUI.H
call append SHOCK\SHKOBJSC.H
call append SHOCK\SHKOBJST.H
call append SHOCK\SHKOPTMN.H
call append SHOCK\SHKMMAX.H
call append SHOCK\SHKMNIID.H
call append SHOCK\SHKMPROP.H
call append SHOCK\SHKMULTI.H
call append SHOCK\SHKMUSIC.H
call append SHOCK\SHKMELPR.H
call append SHOCK\SHKMEL_.C
call append SHOCK\SHKMEL_.H
call append SHOCK\SHKMENU.H
call append SHOCK\SHKMETER.H
call append SHOCK\SHKMFDDM.H
call append SHOCK\SHKMINIG.H
call append SHOCK\SHKLOOP.H
call append SHOCK\SHKLOOT.H
call append SHOCK\SHKMAIN.H
call append SHOCK\SHKMAP.H
call append SHOCK\SHKMELAB.H
call append SHOCK\SHKMELEE.H
call append SHOCK\SHKLABEL.H
call append SHOCK\SHKLBOX.H
call append SHOCK\SHKLDING.H
call append SHOCK\SHKLINKS.H
call append SHOCK\SHKLOOKO.H
call append SHOCK\SHKLOOP.C
call append SHOCK\SHKINIT.H
call append SHOCK\SHKINV.H
call append SHOCK\SHKINVPR.H
call append SHOCK\SHKKEY.H
call append SHOCK\SHKKEYPD.H
call append SHOCK\SHKHRM.H
call append SHOCK\SHKHUD.H
call append SHOCK\SHKIFACE.H
call append SHOCK\SHKIFSTR.H
call append SHOCK\SHKIFTUL.H
call append SHOCK\SHKIMCST.H
call append SHOCK\SHKINCST.H
call append SHOCK\SHKINIT.C
call append SHOCK\SHKHAZRD.H
call append SHOCK\SHKHCOMP.H
call append SHOCK\SHKHOME.H
call append SHOCK\SHKHPLUG.H
call append SHOCK\SHKGUIDS.C
call append SHOCK\SHKGUN.H
call append SHOCK\SHKGUNAN.H
call append SHOCK\SHKGUNMD.H
call append SHOCK\SHKGUNPR.H
call append SHOCK\SHKHACKS.H
call append SHOCK\SHKHAZPR.H
call append SHOCK\SHKFROB.H
call append SHOCK\SHKFSYS.H
call append SHOCK\SHKGAME.H
call append SHOCK\SHKGANPR.H
call append SHOCK\SHKGNAPI.H
call append SHOCK\SHKGNBAS.H
call append SHOCK\SHKDRPRP.H
call append SHOCK\SHKELEV.H
call append SHOCK\SHKEMAIL.H
call append SHOCK\SHKEXP.H
call append SHOCK\SHKFLASH.H
call append SHOCK\SHKDKYHG.H
call append SHOCK\SHKDLG.H
call append SHOCK\SHKDLGM.C
call append SHOCK\SHKDLGM.H
call append SHOCK\SHKDMG.H
call append SHOCK\SHKDMPRP.H
call append SHOCK\SHKCS.H
call append SHOCK\SHKCTRL.H
call append SHOCK\SHKCURM.H
call append SHOCK\SHKCURPR.H
call append SHOCK\SHKCYBER.H
call append SHOCK\SHKDEBRF.H
call append SHOCK\SHKDIFF.H
call append SHOCK\SHKCRMKY.H
call append SHOCK\SHKCROSS.H
call append SHOCK\SHKCROVR.H
call append SHOCK\SHKCRRUM.H
call append SHOCK\SHKCRSHO.H
call append SHOCK\SHKCRARA.H
call append SHOCK\SHKCRARM.H
call append SHOCK\SHKCRBAR.H
call append SHOCK\SHKCRDRD.H
call append SHOCK\SHKCRET.H
call append SHOCK\SHKCRHUM.H
call append SHOCK\SHKCHKCD.H
call append SHOCK\SHKCMAPI.H
call append SHOCK\SHKCMIID.H
call append SHOCK\SHKCMOBJ.H
call append SHOCK\SHKCNTXT.H
call append SHOCK\SHKCOBPR.H
call append SHOCK\SHKCONT.H
call append SHOCK\SHKBOOKO.H
call append SHOCK\SHKCAM.H
call append SHOCK\SHKCHARG.H
call append SHOCK\SHKCHAT.H
call append SHOCK\SHKCHECK.H
call append SHOCK\SHKAMMOV.H
call append SHOCK\SHKANMSP.H
call append SHOCK\SHKARMOR.H
call append SHOCK\SHKARMPR.H
call append SHOCK\SHKBLOOD.H
call append SHOCK\SHKAITPR.H
call append SHOCK\SHKAITRT.H
call append SHOCK\SHKAIUTL.H
call append SHOCK\SHKAIWND.H
call append SHOCK\SHKALARM.H
call append SHOCK\SHKAISHB.H
call append SHOCK\SHKAISHO.H
call append SHOCK\SHKAISWA.H
call append SHOCK\SHKAISWM.H
call append SHOCK\SHKAITBS.H
call append SHOCK\SHKAIRCP.H
call append SHOCK\SHKAIREB.H
call append SHOCK\SHKAIRNB.H
call append SHOCK\SHKAISBS.H
call append SHOCK\SHKAISC.H
call append SHOCK\SHKAIPR.H
call append SHOCK\SHKAIPRO.H
call append SHOCK\SHKAIPTH.H
call append SHOCK\SHKAIRBS.H
call append SHOCK\SHKAIRCA.H
call append SHOCK\SHKAIJSA.H
call append SHOCK\SHKAIMBS.H
call append SHOCK\SHKAIMC.H
call append SHOCK\SHKAIMUC.H
call append SHOCK\SHKAIPBS.H
call append SHOCK\SHKAIGNT.H
call append SHOCK\SHKAIGRA.H
call append SHOCK\SHKAIJRA.H
call append SHOCK\SHKAIDBS.H
call append SHOCK\SHKAIDMR.H
call append SHOCK\SHKAIDTH.H
call append SHOCK\SHKAIEXP.H
call append SHOCK\SHKAIGBS.H
call append SHOCK\SHKAIGNA.H
call append SHOCK\SHKAICBS.H
call append SHOCK\SHKAICHA.H
call append SHOCK\SHKAICMD.H
call append SHOCK\SHKAICRB.H
call append SIM\AVATAR.H
call append SIM\BOW.H
call append SIM\DOORPHYS.H
call append SIM\PLYRSPD.H
call append SIM\DOORPROP.H
call append SIM\DOORREP.H
call append SIM\EOSAPP.C
call append SIM\WRMEM.H
call append SIM\EOSAPP.H
call append SIM\FLOWPRID.H
call append SIM\GHOST.H
call append SIM\GHOSTAPI.H
call append SIM\GHOSTFLG.H
call append SIM\GHOSTINT.H
call append SIM\GHOSTLST.H
call append SIM\GHOSTMOT.H
call append SIM\GHOSTMSG.H
call append SIM\SIMSTATE.H
call append SIM\SIMTBASE.H
call append SIM\SIMTIME.H
call append SIM\SIMTLOOP.H
call append SIM\WRBSP.H
call append SIM\WRCELL.C
call append SIM\WRCELL.H
call append SIM\WRLOOP.H
call append SIM\RPORTAL.H
call append SIM\SIMBASE.H
call append SIM\SIMDEF.H
call append SIM\SIMFLAGS.H
call append SIM\SIMLOOP.C
call append SIM\SIMLOOP.H
call append SIM\SIMMAN.H
call append SIM\SIMMANID.H
call append SIM\SIMSTATE.C
call append SIM\ROOMPROP.H
call append SIM\ROOMS.H
call append SIM\ROOMSYS.H
call append SIM\ROOMUTIL.H
call append SIM\RPATHFND.H
call append SIM\RPATHS.H
call append SIM\ROOM.H
call append SIM\ROOMBASE.H
call append SIM\ROOMEAX.H
call append SIM\ROOMLOOP.H
call append SIM\ROOMPA.H
call append SIM\PLYRMODE.H
call append SIM\PLYRTYPE.H
call append SIM\PLYRVMOT.H
call append SIM\PLYSKILL.H
call append SIM\POSIID.H
call append SIM\POSPROP.H
call append SIM\PRJCTILE.H
call append SIM\PLYCBLLM.H
call append SIM\PLYRBASE.H
call append SIM\PLYRHDLR.H
call append SIM\PLYRLOOP.H
call append SIM\PLYRMOV.H
call append SIM\OBJOWNER.H
call append SIM\OBJPOS.H
call append SIM\PLAYER.H
call append SIM\PLAYROBJ.H
call append SIM\PLAYTEST.H
call append SIM\PLYABLTY.H
call append SIM\PLYABLT_.H
call append SIM\IAVATAR.H
call append SIM\IOBJNET_.H
call append SIM\OBJDB.H
call append SIM\OBJH2X.H
call append SIM\OBJHP.H
call append SIM\OBJLOOP.H
call append SIM\OBJMAGIC.H
call append SIM\OBJMSG.H
call append SIM\GHOSTRCV.H
call append SIM\GHOSTSHK.H
call append SIM\GHOSTSND.H
call append SIM\GHOSTTYP.H
call append SIM\GHOSTWEP.H
call append SIM\HEADMOVE.H
call append SIM\HEADMOVE.C
call append SIM\GHOSTHST.H
call append SIM\GHOSTMVR.H
call append SIM\GHOSTPHY.H
call append SIM\FLOWARCH.H
call append SIM\GHOSTCFG.H
call append SOUND\AMBBASE.H
call append SOUND\AMBIENT.C
call append SOUND\AMBIENT.H
call append SOUND\AMBIENT_.H
call append SOUND\AMBPROP.H
call append SOUND\APPSFX.H
call append SOUND\APPSFXI.H
call append SOUND\VOCORE.H
call append SOUND\VOCPROP.H
call append SOUND\VOGUID.H
call append SOUND\esnd.h
call append SOUND\esndglue.h
call append SOUND\esndprop.h
call append SOUND\ESNDPRID.H
call append SOUND\PSNDAPI.H
call append SOUND\PSNDINFO.H
call append SOUND\PSNDINST.H
call append SOUND\SPCHPROP.H
call append SOUND\SPCHREQ.H
call append SOUND\SPCHT.H
call append SOUND\SPCHTYPE.H
call append SOUND\SPCHVOC.H
call append SOUND\SPEECH.H
call append SOUND\SONGMISS.H
call append SOUND\SONGPLR.H
call append SOUND\SONGPLRI.H
call append SOUND\SONGUTIL.H
call append SOUND\SPCHBASE.H
call append SOUND\SPCHDOM.H
call append SOUND\SPCHGLUE.H
call append SOUND\SNDPROP.H
call append SOUND\SONG.H
call append SOUND\SONGEDTR.H
call append SOUND\SONGFILE.H
call append SOUND\SONGI.H
call append SOUND\SONGID.H
call append SOUND\SCHYACC.C
call append SOUND\SCHYACC.H
call append SOUND\SNDAPP.H
call append SOUND\SNDGEN.H
call append SOUND\SNDLOOP.H
call append SOUND\SNDNET.H
call append SOUND\SCHFILE.H
call append SOUND\SCHLOOP.C
call append SOUND\SCHLOOP.H
call append SOUND\SCHMSG.H
call append SOUND\SCHPROP.H
call append SOUND\SCHSAMPS.H
call append SOUND\SCHTOK.H
call append SOUND\SCHTYPE.H
call append SOUND\SCHBASE.H
call append SOUND\SCHDB.H
call append SOUND\SCHEMA.H
call append SOUND\SCHEMA_.H
call append SOUND\AUXSND.H
call append SOUND\sndframe.h
call append SOUND\ESNDREAC.H
call append SOUND\METASND.H
call append SOUND\PSND.H
call append UI\BUGTERM.C
call append UI\BUGTERM.H
call append UI\BUTTPANL.H
call append UI\CCOMPOSE.H
call append UI\CMDTERM.C
call append UI\CMDTERM.H
call append UI\GED_WIN.C
call append UI\GED_WIN.H
call append UI\WINUI.H
call append UI\KEYIID.H
call append UI\MOVIE.H
call append UI\PANLGUID.H
call append UI\PNLTULID.H
call append UI\UIAPP.H
call append UI\UILOOP.H
call append UI\WINUI.C
call append UI\UIAMOV.H
call append UI\UIANIM.H
call append UI\UIGAME.H
call append UI\JOYPOLL.H
call append UI\PANLMODE.H
call append UI\PANLTOOL.H
call append WIN32\INCLEX.C
call append WIN32\LINKLEX.C
call append WIN32\MSCHLEX.C
call append WIN32\SCHLEX.C
call append WIN32\SONGLEX.C
call append DARK\AFPFILES.H
call append DARK\BOWSCRPT.H
call append DARK\BRETHIID.H
call append DARK\BRETHPRP.H
call append DARK\CCRHUMAN.H
call append DARK\DRKSAVE.H
call append DARK\DRKSAVUI.H
call append DARK\DRKSCRPT.H
call append DARK\DRKUIRES.H
call append DARK\DRKUISCR.H
call append DARK\DRKVO.H
call append DARK\DRKWBDY.H
call append DARK\DRKWBOW.H
call append DARK\DRKWBOW_.C
call append DARK\DRKWBOW_.H
call append DARK\DRKWSWD.H
call append DARK\DRKWSWD_.C
call append DARK\DRKWSWD_.H
call append DARK\DRK_BIND.H
call append DARK\EIDOSAFP.C
call append DARK\EIDOSAFP.H
call append DARK\FILEPANL.H
call append DARK\GADSLIDE.H
call append DARK\CRSWEEL.C
call append DARK\CRSWEEL.H
call append DARK\CRZOMBIE.C
call append DARK\CRZOMBIE.H
call append DARK\DAICAM.H
call append DARK\DAIELEM.H
call append DARK\DAIFROG.H
call append DARK\DARKAI.H
call append DARK\DBRFGUID.H
call append DARK\DIFFSCRM.H
call append DARK\DRKAFP.H
call append DARK\DRKAMAP.H
call append DARK\DRKBNDUI.H
call append DARK\DRKBOOK.H
call append DARK\DRKINV.C
call append DARK\DRKINV.H
call append DARK\DRKINVID.H
call append DARK\DRKINVPR.H
call append DARK\DRKINVSC.H
call append DARK\DRKINVUI.H
call append DARK\DRKLDOUT.H
call append DARK\DRKSCRS.H
call append DARK\DRKREPRT.H
call append DARK\DRKRLOOP.C
call append DARK\DRKRPHLP.H
call append DARK\DRKRUTIL.H
call append DARK\DRKSOUND.H
call append DARK\DRKSTATS.H
call append DARK\DRKLINKS.H
call append DARK\DRKLOOP.C
call append DARK\DRKLOOP.H
call append DARK\DRKLOOT.H
call append DARK\DRKLOOT_.H
call append DARK\DRKMENU.H
call append DARK\DRKMISID.H
call append DARK\CRAPPA.C
call append DARK\CRAPPA.H
call append DARK\CRBOWARM.C
call append DARK\CRBOWARM.H
call append DARK\CRBUGBST.C
call append DARK\CRBUGBST.H
call append DARK\CRBURRIK.C
call append DARK\CRBURRIK.H
call append DARK\CRCONSTA.C
call append DARK\CRCONSTA.H
call append DARK\CRCRAYMN.C
call append DARK\CRCRAYMN.H
call append DARK\CRCUTTY.C
call append DARK\CRCUTTY.H
call append DARK\CRFROG.C
call append DARK\CRFROG.H
call append DARK\CRHUMAND.C
call append DARK\CRHUMAND.H
call append DARK\CRJOINT.H
call append DARK\CRPLYARM.C
call append DARK\CRPLYARM.H
call append DARK\CRROBOT.H
call append DARK\CRROPE.C
call append DARK\CRROPE.H
call append DARK\CRSMRBT.H
call append DARK\CRSPIDER.C
call append DARK\CRSPIDER.H
call append DARK\CRSPIDSM.H
call append DARK\CRSPIDSM.C
call append DARK\DRKBRETH.H
call append DARK\DRKCHKCD.H
call append DARK\DRKCMBAT.H
call append DARK\DRKCOLOR.H
call append DARK\DRKCRET.H
call append DARK\DRKDEBRF.H
call append DARK\DRKDIFF.H
call append DARK\DRKGAME.H
call append DARK\DRKGOALR.H
call append DARK\DRKGOALT.H
call append DARK\DRKIENUM.H
call append DARK\DRKINIT.C
call append DARK\DRKINIT.H
call append DARK\DRKMISLP.H
call append DARK\DRKMISS.H
call append DARK\DRKMSG.H
call append DARK\DRKNETAP.H
call append DARK\DRKPANID.H
call append DARK\DRKPANL.H
call append DARK\DRKPLINV.H
call append DARK\DRKPWSCR.H
call append DARK\DRKPWUPS.H
call append DARK\DRKREACT.H
call append DARK\DRKREND.C
call append DARK\DRKREND.H
call append DARK\INVTYPE.H
call append DARK\LOOTIID.H
call append DARK\LOOTPROP.H
call append DARK\MESHPROP.H
call append DARK\METAGAME.H
call append DARK\METAGUID.H
call append DARK\PICKBASE.H
call append DARK\PICKLOCK.H
call append DARK\PICKSCRM.H
call append DARK\PICKSCRS.H
call append DARK\PLYSCRPT.H
call append DARK\STATBAR.H
call append DARK\STUBFILE.H
call append DARK\VISMETER.H
call append DARK\WEAPSCPT.H
call append DARK\drkfixpr.h
call append DARK\crspirob.c
call append DARK\crspirob.h
call append DARK\drkscrm.h
call append DEEPC\ACTREACT\DPCDRPRP.H
call append DEEPC\ACTREACT\DPCMPROP.H
call append DEEPC\ACTREACT\DPCPROP.H
call append DEEPC\ACTREACT\DPCPRUTL.H
call append DEEPC\ACTREACT\DPCREACT.H
call append DEEPC\ACTREACT\DPCWSPRP.H
call append DEEPC\AI\DPCAI.H
call append DEEPC\AI\DPCAIABS.H
call append DEEPC\AI\DPCAIBIT.H
call append DEEPC\AI\DPCAICBR.H
call append DEEPC\AI\DPCAICBS.H
call append DEEPC\AI\DPCAIDMR.H
call append DEEPC\AI\DPCAIDTH.H
call append DEEPC\AI\DPCAIGNA.H
call append DEEPC\AI\DPCAIGRA.H
call append DEEPC\AI\DPCAIMBS.H
call append DEEPC\AI\DPCAIMUC.H
call append DEEPC\AI\DPCAIPBS.H
call append DEEPC\AI\DPCAIPR.H
call append DEEPC\AI\DPCAIPRO.H
call append DEEPC\AI\DPCAIPTH.H
call append DEEPC\AI\DPCAIRBS.H
call append DEEPC\AI\DPCAIRCP.H
call append DEEPC\AI\DPCAIREB.H
call append DEEPC\AI\DPCAIRNB.H
call append DEEPC\AI\DPCAISBS.H
call append DEEPC\AI\DPCAITBS.H
call append DEEPC\AI\DPCAIUTL.H
call append DEEPC\AI\DPCAIWND.H
call append DEEPC\AI\DPCSTNRC.H
call append DEEPC\AI\DPCAIDGB.H
call append DEEPC\AI\DPCAICHA.H
call append DEEPC\AI\DPCAICMD.H
call append DEEPC\AI\DPCAICRB.H
call append DEEPC\AI\DPCAIDGA.H
call append DEEPC\ENGFEAT\DPCFROB.H
call append DEEPC\ENGFEAT\DPCFSYS.H
call append DEEPC\GAME\DPCALARM.H
call append DEEPC\GAME\DPCBLOOD.H
call append DEEPC\GAME\DPCCHECK.H
call append DEEPC\GAME\DPCCHKCD.H
call append DEEPC\GAME\DPCCNTXT.H
call append DEEPC\GAME\DPCGOALR.H
call append DEEPC\GAME\DPCGOALT.H
call append DEEPC\GAME\DPCGUIDS.C
call append DEEPC\GAME\DPCHAZPR.H
call append DEEPC\GAME\DPCHAZRD.H
call append DEEPC\GAME\DPCHCOMP.H
call append DEEPC\GAME\DPCHPLUG.H
call append DEEPC\GAME\DPCCROSS.H
call append DEEPC\GAME\DPCDIFF.H
call append DEEPC\GAME\DPCDMPRP.H
call append DEEPC\GAME\DPCELEV.H
call append DEEPC\GAME\DPCEMAIL.H
call append DEEPC\GAME\DPCGAME.H
call append DEEPC\GAME\DPCHRM.H
call append DEEPC\GAME\DPCINIT.H
call append DEEPC\GAME\DPCKEYPD.H
call append DEEPC\GAME\DPCLOOP.C
call append DEEPC\GAME\DPCLOOP.H
call append DEEPC\GAME\DPCLOOT.H
call append DEEPC\GAME\DPCPICK.H
call append DEEPC\GAME\DPCPLPUP.H
call append DEEPC\GAME\DPCREPRT.H
call append DEEPC\GAME\DPCSCOMP.H
call append DEEPC\GAME\DPCSECUR.H
call append DEEPC\GAME\DPCMAIN.H
call append DEEPC\GAME\DPCMAP.H
call append DEEPC\GAME\DPCMISS.H
call append DEEPC\GAME\DPCMNIID.H
call append DEEPC\GAME\DPCPATCH.H
call append DEEPC\GAME\DPCPFIID.H
call append DEEPC\GAME\DPCSPAWN.H
call append DEEPC\GAME\DPCTABLE.C
call append DEEPC\GAME\DPCTLUCT.H
call append DEEPC\GAME\DPCVER.H
call append DEEPC\GAME\DPCWSETT.H
call append DEEPC\INPUT\DPCCTRL.H
call append DEEPC\INPUT\DPCKEY.H
call append DEEPC\INPUT\DPCQBIND.H
call append DEEPC\INPUT\DPC_BIND.H
call append DEEPC\MOTION\DPCCRARA.H
call append DEEPC\MOTION\DPCCRARM.H
call append DEEPC\MOTION\DPCCRBAR.H
call append DEEPC\MOTION\DPCCRDHU.C
call append DEEPC\MOTION\DPCCRDHU.H
call append DEEPC\MOTION\DPCCRDOG.C
call append DEEPC\MOTION\DPCCRDOG.H
call append DEEPC\MOTION\DPCCRDOO.C
call append DEEPC\MOTION\DPCCRDOO.H
call append DEEPC\MOTION\DPCCRDRD.H
call append DEEPC\MOTION\DPCCRET.H
call append DEEPC\MOTION\DPCCRHUM.H
call append DEEPC\MOTION\DPCCRMKY.H
call append DEEPC\MOTION\DPCCROVR.H
call append DEEPC\MP\DPCNET.H
call append DEEPC\MP\DPCNETID.H
call append DEEPC\OBJECT\DPCARMPR.H
call append DEEPC\OBJECT\DPCDMG.H
call append DEEPC\OBJECT\DPCLINKS.H
call append DEEPC\OBJECT\DPCOBJST.H
call append DEEPC\OBJECT\DPCTRCST.H
call append DEEPC\PLAYER\DPCINV.H
call append DEEPC\PLAYER\DPCINVPR.H
call append DEEPC\PLAYER\DPCLOOKO.H
call append DEEPC\PLAYER\DPCMELAB.H
call append DEEPC\PLAYER\DPCMELEE.H
call append DEEPC\PLAYER\DPCMEL_.C
call append DEEPC\PLAYER\DPCMEL_.H
call append DEEPC\PLAYER\DPCPARAM.H
call append DEEPC\PLAYER\DPCPLAYR.H
call append DEEPC\PLAYER\DPCPLDMG.H
call append DEEPC\PLAYER\DPCPLIID.H
call append DEEPC\PLAYER\DPCPLPRP.H
call append DEEPC\PLAYER\DPCPLTYP.H
call append DEEPC\PLAYER\DPCSTCST.H
call append DEEPC\PLAYER\DPCTECH.H
call append DEEPC\RENDER\DPCANMSP.H
call append DEEPC\RENDER\DPCCAM.H
call append DEEPC\RENDER\DPCCMAPI.H
call append DEEPC\RENDER\DPCCMIID.H
call append DEEPC\RENDER\DPCCMOBJ.H
call append DEEPC\RENDER\DPCCOBPR.H
call append DEEPC\RENDER\DPCCS.H
call append DEEPC\RENDER\DPCREND.C
call append DEEPC\RENDER\DPCREND.H
call append DEEPC\RENDER\DPCRNDOV.H
call append DEEPC\RENDER\DPCUTILS.H
call append DEEPC\RENDER\DPCVHOT.H
call append DEEPC\SCRIPTS\DPCAISC.H
call append DEEPC\SCRIPTS\DPCHOME.H
call append DEEPC\SCRIPTS\DPCSCAPI.H
call append DEEPC\SCRIPTS\DPCSCRM.H
call append DEEPC\SCRIPTS\DPCSCRPT.H
call append DEEPC\SCRIPTS\DPCSCRS.H
call append DEEPC\SCRIPTS\DPCTRIP.H
call append DEEPC\SCRIPTS\DPCWEPSC.H
call append DEEPC\SOUND\DPCSNDPR.H
call append DEEPC\SOUND\DPCSOUND.H
call append DEEPC\UI\DPCBOOKO.H
call append DEEPC\UI\DPCCHAT.H
call append DEEPC\UI\DPCCONT.H
call append DEEPC\UI\DPCCURM.H
call append DEEPC\UI\DPCCURPR.H
call append DEEPC\UI\DPCDLG.H
call append DEEPC\UI\DPCHUD.H
call append DEEPC\UI\DPCIFACE.H
call append DEEPC\UI\DPCIFSTR.H
call append DEEPC\UI\DPCIFTUL.H
call append DEEPC\UI\DPCINCST.H
call append DEEPC\UI\DPCLBOX.H
call append DEEPC\UI\DPCLDING.H
call append DEEPC\UI\DPCMENU.H
call append DEEPC\UI\DPCMETER.H
call append DEEPC\UI\DPCMFDDM.H
call append DEEPC\UI\DPCMULTI.H
call append DEEPC\UI\DPCNETUI.H
call append DEEPC\UI\DPCOPTMN.H
call append DEEPC\UI\DPCOVCST.H
call append DEEPC\UI\DPCOVRLY.H
call append DEEPC\UI\DPCPDA.H
call append DEEPC\UI\DPCPDCST.H
call append DEEPC\UI\DPCSAVUI.H
call append DEEPC\UI\DPCSVBND.H
call append DEEPC\UI\DPCUITUL.H
call append DEEPC\UI\DPCYORN.H
call append DEEPC\WEAPON\DPCAMMOV.H
call append DEEPC\WEAPON\DPCFLASH.H
call append DEEPC\WEAPON\DPCGANPR.H
call append DEEPC\WEAPON\DPCGNAPI.H
call append DEEPC\WEAPON\DPCGNBAS.H
call append DEEPC\WEAPON\DPCGUNAN.H
call append DEEPC\WEAPON\DPCGUNMD.H
call append DEEPC\WEAPON\DPCGUNPR.H
call append DEEPC\WEAPON\DPCMELPR.H
call append DEEPC\WEAPON\DPCPGAPI.H
call append DEEPC\WEAPON\DPCPJBAS.H
call append DEEPC\WEAPON\DPCPLCST.H
call append DEEPC\WEAPON\DPCPRJPR.H
call append DEEPC\WEAPON\DPCPROJ.H
call append EDITOR\ALIGNPNP.C
call append EDITOR\AREAPNP.C
call append EDITOR\AREAPNP.H
call append EDITOR\AUTOVBR.H
call append EDITOR\BLDSTAIR.C
call append EDITOR\BLDSTAIR.H
call append EDITOR\BRESTORE.H
call append EDITOR\BRINFO.C
call append EDITOR\BRINFO.H
call append EDITOR\BRLIST.C
call append EDITOR\BRLIST.H
call append EDITOR\BRLOOP.C
call append EDITOR\BRLOOP.H
call append EDITOR\BROBJPRO.H
call append EDITOR\BRPROP.H
call append EDITOR\BRQUERY.C
call append EDITOR\BRQUERY.H
call append EDITOR\BRREND.C
call append EDITOR\BRREND.H
call append EDITOR\BRTYPES.H
call append EDITOR\BRUNDO.C
call append EDITOR\BRUNDO.H
call append EDITOR\BRUSHGFH.C
call append EDITOR\BRUSHGFH.H
call append EDITOR\CMDBUTTS.C
call append EDITOR\CMDBUTTS.H
call append EDITOR\CSGBRUSH.H
call append EDITOR\CVTBRUSH.C
call append EDITOR\CVTBRUSH.H
call append EDITOR\CYCLEGAD.C
call append EDITOR\CYCLEGAD.H
call append EDITOR\DOORBLOK.H
call append EDITOR\DRAGBOX.C
call append EDITOR\DRAGBOX.H
call append EDITOR\EDINHST.H
call append EDITOR\EDINHTYP.H
call append EDITOR\EDITAPP.C
call append EDITOR\EDITAPP.H
call append EDITOR\EDITBR.C
call append EDITOR\EDITBR.H
call append EDITOR\EDITBRS.H
call append EDITOR\EDITBR_.H
call append EDITOR\EDITGEOM.C
call append EDITOR\EDITGEOM.H
call append EDITOR\EDITGEO_.H
call append EDITOR\EDITINH.H
call append EDITOR\EDITLINK.H
call append EDITOR\EDITMODE.C
call append EDITOR\EDITMODE.H
call append EDITOR\EDITOBJ.C
call append EDITOR\EDITOBJ.H
call append EDITOR\EDITPLST.H
call append EDITOR\EDITPROP.C
call append EDITOR\EDITPROP.H
call append EDITOR\EDITPRST.H
call append EDITOR\EDITSAVE.C
call append EDITOR\EDITSAVE.H
call append EDITOR\EDITTUL_.H
call append EDITOR\EDLINKST.H
call append EDITOR\EDLNKTYP.H
call append EDITOR\EDMEDMO.C
call append EDITOR\EDMEDMO.H
call append EDITOR\EDMEDMOS.H
call append EDITOR\EDMEDMOT.H
call append EDITOR\FAMEDIT.H
call append EDITOR\FILEMENU.H
call append EDITOR\FVAREDIT.H
call append EDITOR\gedit.c
call append EDITOR\GEDIT.H
call append EDITOR\GEDMEDMO.C
call append EDITOR\GEDMEDMO.H
call append EDITOR\GED_CSG.H
call append EDITOR\GED_LINE.C
call append EDITOR\GED_LINE.H
call append EDITOR\GED_REND.C
call append EDITOR\GED_REND.H
call append EDITOR\GED_RMAP.C
call append EDITOR\GED_RMAP.H
call append EDITOR\GED_ROOM.H
call append EDITOR\GED_UNDO.C
call append EDITOR\GED_UNDO.H
call append EDITOR\GFHFROBS.C
call append EDITOR\GFHFROBS.H
call append EDITOR\GRIDPNP.C
call append EDITOR\GRIDSNAP.C
call append EDITOR\GRIDSNAP.H
call append EDITOR\HILIGHT.C
call append EDITOR\HILIGHT.H
call append EDITOR\ISDESCED.H
call append EDITOR\ISDESCST.H
call append EDITOR\ISDESCTY.H
call append EDITOR\LGSLIDER.C
call append EDITOR\LGSLIDER.H
call append EDITOR\LIGHTPNP.C
call append EDITOR\LINKDRAW.H
call append EDITOR\LINKEDIT.H
call append EDITOR\LNKTRAIT.H
call append EDITOR\LNKTRAI_.H
call append EDITOR\MEDFLBOX.C
call append EDITOR\MEDFLBOX.H
call append EDITOR\MEDIFACE.C
call append EDITOR\MEDIFACE.H
call append EDITOR\MEDMENU.H
call append EDITOR\MEDPLAY.H
call append EDITOR\MENUS.H
call append EDITOR\MODALUI.C
call append EDITOR\MODALUI.H
call append EDITOR\MOTEDIT.H
call append EDITOR\MOTEDIT_.H
call append EDITOR\NAMENUM.C
call append EDITOR\NAMENUM.H
call append EDITOR\OBJEDIT.H
call append EDITOR\OBJHISTP.H
call append EDITOR\OBJPNP.C
call append EDITOR\OTREEED.H
call append EDITOR\PNPTOOLS.C
call append EDITOR\PNPTOOLS.H
call append EDITOR\PNPTOOL_.H
call append EDITOR\PNPVSLID.H
call append EDITOR\PRELOAD.C
call append EDITOR\PRELOAD.H
call append EDITOR\PRIMAL.C
call append EDITOR\PRIMAL.H
call append EDITOR\PRIMALS.H
call append EDITOR\PRIMFAST.H
call append EDITOR\PRIMSHAP.C
call append EDITOR\PRIMSHAP.H
call append EDITOR\PROMPTS.C
call append EDITOR\PROMPTS.H
call append EDITOR\PROPED.H
call append EDITOR\PROPTEST.H
call append EDITOR\PSDIALOG.H
call append EDITOR\QUESEDIT.H
call append EDITOR\RENDTEST.C
call append EDITOR\RENDTEST.H
call append EDITOR\ROOMPNP.C
call append EDITOR\SAVELOAD.C
call append EDITOR\ROOMTOWR.H
call append EDITOR\SAVELOAD.H
call append EDITOR\SCRNEDIT.H
call append EDITOR\SCRPTED.H
call append EDITOR\SDESEDIT.H
call append EDITOR\SDESEDST.H
call append EDITOR\SDESPARM.H
call append EDITOR\SIMPWRAP.H
call append EDITOR\STATUS.C
call append EDITOR\STATUS.H
call append EDITOR\STUPIDUI.C
call append EDITOR\STUPIDUI.H
call append EDITOR\SWAPPNP.C
call append EDITOR\SWAPPNP.H
call append EDITOR\SWAPREGS.C
call append EDITOR\SWAPTOOL.C
call append EDITOR\SWAPTOOL.H
call append EDITOR\TXTPNP.C
call append EDITOR\TXTPNP.H
call append EDITOR\TXTRPAL.C
call append EDITOR\TXTRPAL.H
call append EDITOR\UIEDIT.C
call append EDITOR\UIEDIT.H
call append EDITOR\UNDOREDO.C
call append EDITOR\UNDOREDO.H
call append EDITOR\USERPNP.C
call append EDITOR\VBRUSH.C
call append EDITOR\USERPNP.H
call append EDITOR\VBRUSH.H
call append EDITOR\VBR_MATH.C
call append EDITOR\VIEWMGR.C
call append EDITOR\VBR_MATH.H
call append EDITOR\VIEWMGR.H
call append EDITOR\VIEWMGR_.H
call append EDITOR\VMWINCFG.C
call append EDITOR\VMWINCFG.H
call append EDITOR\VSLIDER.C
call append EDITOR\VSLIDER.H
call append EDITOR\VSLIDERG.H
call append EDITOR\VUMANUI.C
call append EDITOR\VUMANUI.H
call append ENGFEAT\AMAPGUID.H
call append ENGFEAT\AUTOMAP.H
call append ENGFEAT\AUTOPROP.H
call append ENGFEAT\CAMPAIGN.H
call append ENGFEAT\CMPGNIID.H
call append ENGFEAT\CMPGNMSG.H
call append ENGFEAT\COMBPROP.H
call append ENGFEAT\CONTAIN.H
call append ENGFEAT\CONTIID.H
call append ENGFEAT\CONTPROP.H
call append ENGFEAT\CULPABLE.H
call append ENGFEAT\DMGBASE.H
call append ENGFEAT\DMGGUID.H
call append ENGFEAT\DMGMODEL.H
call append ENGFEAT\DMGMODL_.H
call append ENGFEAT\DMGPROP.H
call append ENGFEAT\ENGFEAT.H
call append ENGFEAT\ENGFLOOP.H
call append ENGFEAT\ENGFPROP.H
call append ENGFEAT\FLINDER.H
call append ENGFEAT\FROBCTRL.H
call append ENGFEAT\FROBPROP.H
call append ENGFEAT\GUNANIM.H
call append ENGFEAT\GUNAPI.H
call append ENGFEAT\GUNBASE.H
call append ENGFEAT\GUNFLASH.H
call append ENGFEAT\GUNPROP.H
call append ENGFEAT\HPPROP.H
call append ENGFEAT\INVLIMB.H
call append ENGFEAT\INVRGUID.H
call append ENGFEAT\INVRNDPR.H
call append ENGFEAT\INV_HACK.C
call append ENGFEAT\INV_HACK.H
call append ENGFEAT\INV_REND.C
call append ENGFEAT\INV_REND.H
call append ENGFEAT\KEYPROP.H
call append ENGFEAT\KEYSYS.H
call append ENGFEAT\KEYTYPE.H
call append ENGFEAT\LOCKPROP.H
call append ENGFEAT\MEDIA.H
call append ENGFEAT\MEDIAOP.H
call append ENGFEAT\NZPRUTIL.H
call append ENGFEAT\OWNPROP.H
call append ENGFEAT\PICK.H
call append ENGFEAT\PRELDPRP.H
call append ENGFEAT\PROJBASE.H
call append ENGFEAT\PROJLINK.H
call append ENGFEAT\PROJPROP.H
call append ENGFEAT\PROPREAC.H
call append ENGFEAT\QUESFILE.H
call append ENGFEAT\QUESLOOP.H
call append ENGFEAT\QUESREAC.H
call append ENGFEAT\QUEST.H
call append ENGFEAT\QUESTAPI.H
call append ENGFEAT\QUESTIID.H
call append ENGFEAT\QUESTPRP.H
call append ENGFEAT\QVPROPID.H
call append ENGFEAT\SIMPDMG_.H
call append ENGFEAT\SIMPLDMG.H
call append ENGFEAT\SUSPROP.H
call append ENGFEAT\TFINT.H
call append ENGFEAT\TRAPPROP.H
call append ENGFEAT\TWEQBASE.H
call append ENGFEAT\TWEQCTRL.H
call append ENGFEAT\TWEQENUM.H
call append ENGFEAT\TWEQEXP.H
call append ENGFEAT\TWEQFLGS.H
call append ENGFEAT\TWEQPROP.H
call append ENGFEAT\TWEQREP.H
call append ENGFEAT\TWQPROP_.H
call append ENGFEAT\WEAPBOW.H
call append ENGFEAT\WEAPCB.H
call append ENGFEAT\WEAPGUID.H
call append ENGFEAT\WEAPHALO.H
call append ENGFEAT\WEAPHIT.H
call append ENGFEAT\WEAPON.H
call append ENGFEAT\WEAPPROP.H
call append ENGFEAT\WEAPREAC.H
call append ENGFEAT\X10GUISH.H
call append FRAMEWRK\2DAPP.C
call append FRAMEWRK\2DAPP.H
call append FRAMEWRK\APPNAME.C
call append FRAMEWRK\APPNAME.H
call append FRAMEWRK\BACKUP.H
call append FRAMEWRK\BASEMODE.C
call append FRAMEWRK\BASEMODE.H
call append FRAMEWRK\CDCONST.H
call append FRAMEWRK\CDGUID.H
call append FRAMEWRK\CDPLAYER.H
call append FRAMEWRK\CFGTOOL.C
call append FRAMEWRK\CFGTOOL.H
call append FRAMEWRK\CHAINEVT.H
call append FRAMEWRK\COMMAND.C
call append FRAMEWRK\COMMAND.H
call append FRAMEWRK\CONTEXTS.H
call append FRAMEWRK\CTAGNET.H
call append FRAMEWRK\DAPPSINK.H
call append FRAMEWRK\DBASEMSG.H
call append FRAMEWRK\DBFILE.H
call append FRAMEWRK\DBTAGFIL.H
call append FRAMEWRK\DBTYPE.H
call append FRAMEWRK\DISKFREE.C
call append FRAMEWRK\DISKFREE.H
call append FRAMEWRK\DISPAPP.H
call append FRAMEWRK\DISPATCH.H
call append FRAMEWRK\DISPBASE.H
call append FRAMEWRK\DLGLOOP.C
call append FRAMEWRK\DLGLOOP.H
call append FRAMEWRK\DLGMODE.C
call append FRAMEWRK\DLGMODE.H
call append FRAMEWRK\DPSHELL.H
call append FRAMEWRK\DSPCHDEF.H
call append FRAMEWRK\DSPCHIID.H
call append FRAMEWRK\DWORDSET.H
call append FRAMEWRK\DXLOAD.H
call append FRAMEWRK\DXWRNDLG.H
call append FRAMEWRK\FASTFLTS.H
call append FRAMEWRK\FCYTAGDB.H
call append FRAMEWRK\FILETOOL.C
call append FRAMEWRK\GAMEAPP.C
call append FRAMEWRK\FILETOOL.H
call append FRAMEWRK\FILEVAR.H
call append FRAMEWRK\FIXTIME.H
call append FRAMEWRK\FLTANG.H
call append FRAMEWRK\FVARLOOP.H
call append FRAMEWRK\GAMEAPP.H
call append FRAMEWRK\GAMECAM.H
call append FRAMEWRK\GAMEIID.C
call append FRAMEWRK\GAMEINFO.C
call append FRAMEWRK\GAMEINFO.H
call append FRAMEWRK\GAMEMODE.C
call append FRAMEWRK\GAMEMODE.H
call append FRAMEWRK\GAMEMSG.H
call append FRAMEWRK\GAMESCRN.H
call append FRAMEWRK\GAMESPEC.H
call append FRAMEWRK\GAMESTR.H
call append FRAMEWRK\GAMETABL.H
call append FRAMEWRK\GAMETOOL.H
call append FRAMEWRK\GEN_BIND.H
call append FRAMEWRK\HCHKTHRD.H
call append FRAMEWRK\HYBTABLE.C
call append FRAMEWRK\IDISPATC.H
call append FRAMEWRK\IDISPAT_.H
call append FRAMEWRK\IMGSRC.H
call append FRAMEWRK\IMGSRCID.H
call append FRAMEWRK\INETSTAT.H
call append FRAMEWRK\INIT.H
call append FRAMEWRK\LOOPAPP.C
call append FRAMEWRK\LOOPAPP.H
call append FRAMEWRK\LOOPMSG.H
call append FRAMEWRK\LRESDISK.C
call append FRAMEWRK\LRESDISK.H
call append FRAMEWRK\LRESHASH.H
call append FRAMEWRK\LRESNAME.C
call append FRAMEWRK\LRESNAME.H
call append FRAMEWRK\LRESS.H
call append FRAMEWRK\LRESTOK.H
call append FRAMEWRK\LRES_.H
call append FRAMEWRK\LR_CACHE.H
call append FRAMEWRK\MATRIXC.H
call append FRAMEWRK\NAMEMAP.H
call append FRAMEWRK\NETAPP.H
call append FRAMEWRK\NETLOOP.H
call append FRAMEWRK\NETMSG.H
call append FRAMEWRK\NETSIM.H
call append FRAMEWRK\NETSYNCH.H
call append FRAMEWRK\NETVOICE.H
call append FRAMEWRK\PICKGAME.H
call append FRAMEWRK\R3APP.C
call append FRAMEWRK\R3APP.H
call append FRAMEWRK\RAND.H
call append FRAMEWRK\REPORT.H
call append FRAMEWRK\REPRTHLP.H
call append FRAMEWRK\REPUTIL.H
call append FRAMEWRK\RESAPP.C
call append FRAMEWRK\RESAPP.H
call append FRAMEWRK\RESDATA.C
call append FRAMEWRK\RESDATA.H
call append FRAMEWRK\SUBSCRIP.H
call append FRAMEWRK\TAG.H
call append FRAMEWRK\TAGBASE.H
call append FRAMEWRK\TAGCONST.H
call append FRAMEWRK\TAGDBDAT.H
call append FRAMEWRK\TAGDBIN.H
call append FRAMEWRK\TAGDBKEY.H
call append FRAMEWRK\TAGDBKST.H
call append FRAMEWRK\TAGDBOUT.H
call append FRAMEWRK\TAGDBT.H
call append FRAMEWRK\TAGPATCH.H
call append FRAMEWRK\TAGTYPE.H
call append FRAMEWRK\ctag.h
call append FRAMEWRK\ctagset.h
call append FRAMEWRK\tagremap.h
call append FRAMEWRK\RESDEFS2.H
call append FRAMEWRK\RESLOOP.H
call append FRAMEWRK\RESOURCE.H
call append FRAMEWRK\RESPATHS.H
call append FRAMEWRK\RN_CNVRT.H
call append FRAMEWRK\SCRNDUMP.H
call append FRAMEWRK\RESLOOP.C
call append FRAMEWRK\RN_CNVRT.C
call append FRAMEWRK\btffact.h
call append FRAMEWRK\buftagf.h
call append MOTION\BIPLOOP.C
call append MOTION\BIPLOOP.H
call append MOTION\CRATTACH.H
call append MOTION\CREATURE.H
call append MOTION\CRETPROP.H
call append MOTION\mschtype.h
call append MOTION\mseltype.h
call append MOTION\mtagvals.h
call append MOTION\CREXP.H
call append MOTION\CRJOINT.H
call append MOTION\CRWPNAPI.H
call append MOTION\CRWPNLST.H
call append MOTION\CRWPNLUP.H
call append MOTION\IMOTIID.H
call append MOTION\IMOTTAB.H
call append MOTION\LOCOBASE.H
call append MOTION\motdesc.h
call append MOTION\motdmnge.h
call append MOTION\motorapi.h
call append MOTION\motrtype.h
call append MOTION\motschem.h
call append MOTION\motset.h
call append MOTION\mottype.h
call append MOTION\mputil.h
call append MOTION\mschbase.h
call append MOTION\mschtok.h
call append MOTION\mctype.h
call append MOTION\mctype_.h
call append MOTION\meshapi.h
call append MOTION\mmanuver.h
call append MOTION\mmnvrfac.h
call append MOTION\mmresapi.h
call append MOTION\motbase.h
call append MOTION\motdb_.h
call append MOTION\motdbase.h
call append MOTION\motdbtyp.h
call append MOTION\SKILLSET.H
call append MOTION\SKILLTAB.H
call append MOTION\SKILLTYP.H
call append MOTION\cbllmapi.h
call append MOTION\cbllmtyp.h
call append MOTION\creatapi.h
call append MOTION\creatext.h
call append MOTION\creatur_.h
call append MOTION\crettype.h
call append MOTION\mcoord.h
call append MOTION\MVRUTILS.H
call append MOTION\PUPPET.H
call append MOTION\PUPPROP.H
call append MOTION\SKILDTAB.C
call append MOTION\SKILDTAB.H
call append MOTION\MCLNTAPI.H
call append MOTION\MOTDB.H
call append MOTION\MOTDMNG_.H
call append MOTION\MOTMNGR.H
call append MOTION\MOTPROP.H
call append MOTION\MSCHUTIL.H
call append MOTION\MSCHYACC.H
call append MOTION\MSKILSET.H
call append MOTION\MSKLTREE.H
call append MOTION\MSKLTYPE.H
call append MOTION\MOTDMNGE.C
call append MOTION\MVRFLAGS.H
call append MOTION\MSCHYACC.C
call append OBJECT\AUTOLINK.H
call append OBJECT\BINTRAIT.H
call append OBJECT\COMPARRB.H
call append OBJECT\COMPARRY.H
call append OBJECT\DATAOPS.H
call append OBJECT\DATAOPST.H
call append OBJECT\DATAOPS_.H
call append OBJECT\DATOPIID.H
call append OBJECT\TRAITQDB.H
call append OBJECT\TRAITTYP.H
call append OBJECT\TRAIT_.H
call append OBJECT\TRCACHE.H
call append OBJECT\TRCACHE_.H
call append OBJECT\TRCACHUI.H
call append OBJECT\objarray.h
call append OBJECT\DLISTSIM.H
call append OBJECT\TRAITLNK.H
call append OBJECT\TRAITLN_.H
call append OBJECT\TRAITMAN.H
call append OBJECT\TRAITMA_.H
call append OBJECT\TRAITNUL.H
call append OBJECT\TRAITPRP.H
call append OBJECT\TRAITPR_.H
call append OBJECT\STRPROP_.H
call append OBJECT\TCACHIID.H
call append OBJECT\TRAISRCH.H
call append OBJECT\TRAIT.H
call append OBJECT\TRAITBAS.H
call append OBJECT\TRAITIID.C
call append OBJECT\TRAITIID.H
call append OBJECT\RELATION.H
call append OBJECT\RELATIO_.H
call append OBJECT\RELDELEG.H
call append OBJECT\RELINVER.H
call append OBJECT\RELNULL.H
call append OBJECT\RELTYPE.H
call append OBJECT\SDESC.H
call append OBJECT\PROPSPRS.H
call append OBJECT\PROPSTAT.H
call append OBJECT\PROPSTOR.H
call append OBJECT\PROPSTO_.H
call append OBJECT\PROPTYPE.H
call append OBJECT\PROPVAL_.H
call append OBJECT\QUERYNUL.H
call append OBJECT\PRPSTATS.H
call append OBJECT\PSTORDEL.H
call append OBJECT\PROPNAME.H
call append OBJECT\PROPNET.H
call append OBJECT\PROPNULL.H
call append OBJECT\PROPOBSV.H
call append OBJECT\PROPRAW.H
call append OBJECT\PROPRAW_.H
call append OBJECT\PROPSCPT.H
call append OBJECT\PROPSIMP.H
call append OBJECT\PROPLINK.H
call append OBJECT\PROPLIST.H
call append OBJECT\PROPLNK_.H
call append OBJECT\PROPMAN.H
call append OBJECT\PROPMAN_.H
call append OBJECT\PROPMIX.H
call append OBJECT\PROPGUID.H
call append OBJECT\PROPHASH.H
call append OBJECT\PROPID.H
call append OBJECT\PROPIMP.H
call append OBJECT\PROPINST.H
call append OBJECT\PROPINV.H
call append OBJECT\PROPINVC.H
call append OBJECT\PROPINVS.H
call append OBJECT\PROPKNOW.H
call append OBJECT\PROPCOMP.H
call append OBJECT\PROPDB.H
call append OBJECT\PROPDEF.H
call append OBJECT\PROPERTY.H
call append OBJECT\PROPERT_.H
call append OBJECT\PROPFACE.H
call append OBJECT\PROPFAC_.H
call append OBJECT\PROPGUID.C
call append OBJECT\PROPARRY.H
call append OBJECT\PROPBASE.H
call append OBJECT\PROPCARY.H
call append OBJECT\objspace.h
call append OBJECT\PROPBOOL.H
call append OBJECT\OBJTYPE.H
call append OBJECT\OSETLNKQ.H
call append OBJECT\OSYSBASE.H
call append OBJECT\PRCNITER.H
call append OBJECT\OSYSTYPE.H
call append OBJECT\OTREEBAS.H
call append OBJECT\OTREETYP.H
call append OBJECT\PFACEIID.H
call append OBJECT\PFACINIT.H
call append OBJECT\OBJNOTIF.H
call append OBJECT\OBJPROXY.H
call append OBJECT\OBJQUERY.H
call append OBJECT\OBJQUER_.H
call append OBJECT\OBJREMAP.H
call append OBJECT\OBJSTAT.H
call append OBJECT\OBJSYS.H
call append OBJECT\NETMNIID.H
call append OBJECT\NETNOTIF.H
call append OBJECT\NETPROPS.H
call append OBJECT\NETTYPES.H
call append OBJECT\OBJDEF.H
call append OBJECT\OBJEDBAS.H
call append OBJECT\OBJEDIID.H
call append OBJECT\OBJEDTYP.H
call append OBJECT\OBJLPARS.H
call append OBJECT\LNKBYOBJ.H
call append OBJECT\LNKDTABL.H
call append OBJECT\LNKQUERY.H
call append OBJECT\LNKQUER_.H
call append OBJECT\LNKREMAP.H
call append OBJECT\LSTSTTEM.H
call append OBJECT\NAMEPROP.H
call append OBJECT\NETMAN.H
call append OBJECT\LINKQDB.H
call append OBJECT\LINKQDB_.H
call append OBJECT\LINKSET.H
call append OBJECT\LINKSTOR.H
call append OBJECT\LINKSTO_.H
call append OBJECT\LINKTYPE.H
call append OBJECT\LINKVIEW.H
call append OBJECT\LISTSET.H
call append OBJECT\LINKINT.H
call append OBJECT\LINKINTB.H
call append OBJECT\LINKKNOW.H
call append OBJECT\LINKLOOP.H
call append OBJECT\LINKMAN.H
call append OBJECT\LINKMAN_.H
call append OBJECT\LINKPROP.H
call append OBJECT\LINKBASE.H
call append OBJECT\LINKBOTH.H
call append OBJECT\LINKDAT_.H
call append OBJECT\LINKDB_.H
call append OBJECT\LINKEDST.H
call append OBJECT\LINKGUID.C
call append OBJECT\LINKGUID.H
call append OBJECT\LINKID.H
call append OBJECT\GUNGUID.H
call append OBJECT\IOBJED.H
call append OBJECT\IOBJNET.H
call append OBJECT\IOBJSYS.H
call append OBJECT\IOBJSYS_.H
call append OBJECT\LABEL.H
call append OBJECT\LAZYAGG.H
call append OBJECT\LINK.H
call append OBJECT\LINKARRY.H
call append OBJECT\DONORQ.H
call append OBJECT\DONORQ_.H
call append OBJECT\ETOOLIID.H
call append OBJECT\EDITTOOL.H
call append OBJECT\EDTRAIST.H
call append OBJECT\EDTRAIT.H
call append OBJECT\EDTRAITY.H
call append PHYSICS\CATTYPE.H
call append PHYSICS\COLLIDE.H
call append PHYSICS\COLLPROP.H
call append PHYSICS\GUNPROJ.H
call append PHYSICS\GUNVHOT.H
call append PHYSICS\SPHERCHK.H
call append PHYSICS\OBJMEDIA.H
call append PHYSICS\PHCLIMB.H
call append PHYSICS\PHCLSN.H
call append PHYSICS\PHCONST.H
call append PHYSICS\PHCONTCT.H
call append PHYSICS\PHCORE.H
call append PHYSICS\PHCTRL.H
call append PHYSICS\PHDBG.H
call append PHYSICS\PHDYN.H
call append PHYSICS\PHUTILS.H
call append PHYSICS\PHYSAPI.H
call append PHYSICS\PHYSCAST.H
call append PHYSICS\PHYSLOOP.H
call append PHYSICS\PHYSTEST.H
call append PHYSICS\PHYSTYP2.H
call append PHYSICS\PHREPORT.H
call append PHYSICS\PHSCRPT.H
call append PHYSICS\PHSCRT.H
call append PHYSICS\PHSUBMOD.H
call append PHYSICS\PHTERR.H
call append PHYSICS\PHTXTPRP.H
call append PHYSICS\PHOPROP.H
call append PHYSICS\PHPOS.H
call append PHYSICS\PHPPSCPT.H
call append PHYSICS\PHPROP.H
call append PHYSICS\PHPROPS.H
call append PHYSICS\PHREF.H
call append PHYSICS\PHMSG.H
call append PHYSICS\PHMTERR.H
call append PHYSICS\PHMTPROP.H
call append PHYSICS\PHMTSCPT.H
call append PHYSICS\PHNET.H
call append PHYSICS\PHMODOBB.H
call append PHYSICS\PHMODS.H
call append PHYSICS\PHMODSPH.H
call append PHYSICS\PHMODUTL.H
call append PHYSICS\PHMOTION.H
call append PHYSICS\PHLISTYP.H
call append PHYSICS\PHMEDTR.H
call append PHYSICS\PHMOAPI.H
call append PHYSICS\PHMOD.H
call append PHYSICS\PHMODATA.C
call append PHYSICS\PHMODATA.H
call append PHYSICS\PHMODBSP.H
call append PHYSICS\PHFLIST.H
call append PHYSICS\PHLISBAS.H
call append PHYSICS\PHLISTN_.H
call append PHYSICS\PHCOLLEV.H
call append PORTAL\ANIMLIT.C
call append PORTAL\ANIMLIT.H
call append PORTAL\BSPSPHR.C
call append PORTAL\BSPSPHR.H
call append PORTAL\CHAR.C
call append PORTAL\CHAR.H
call append PORTAL\DUV.C
call append PORTAL\MAPPER.C
call append PORTAL\MAPPER.H
call append PORTAL\WRTYPE.H
call append PORTAL\ORACLE.H
call append PORTAL\ORACLE_.H
call append PORTAL\OUROBJ.H
call append PORTAL\PERFCORE.H
call append PORTAL\POINT.H
call append PORTAL\PORT.H
call append PORTAL\PORTAL.H
call append PORTAL\PORTAL_.H
call append PORTAL\PORTCLIP.H
call append PORTAL\WR.H
call append PORTAL\WRCAST.C
call append PORTAL\WRCAST_.H
call append PORTAL\WRDB.C
call append PORTAL\WRDB.H
call append PORTAL\WRDBG.C
call append PORTAL\WRDBREND.H
call append PORTAL\WRFUNC.C
call append PORTAL\PORTAL.C
call append PORTAL\WRFUNC.H
call append PORTAL\WRLIMIT.H
call append PORTAL\WROBJ.H
call append PORTAL\PTSURF.H
call append PORTAL\PT_ALIGN.H
call append PORTAL\PT_ASM.H
call append PORTAL\PT_CLUT.C
call append PORTAL\PT_CLUT.H
call append PORTAL\PT_MAIN.C
call append PORTAL\PT_MEM.C
call append PORTAL\RECIP.H
call append PORTAL\SURFACES.C
call append PORTAL\PTDRAWHW.C
call append PORTAL\PTMAP.H
call append PORTAL\PTMAPPER.H
call append PORTAL\PORTHW.H
call append PORTAL\PORTLIT.C
call append PORTAL\PORTMAIN.C
call append PORTAL\PORTPICK.C
call append PORTAL\PORTSKY.C
call append PORTAL\PORTSKY.H
call append PORTAL\PORTSURF.C
call append PORTAL\PORTWATR.C
call append PORTAL\PORTWATR.H
call append PORTAL\PROFILE.H
call append PORTAL\PT.H
call append PORTAL\PORTDRAW.H
call append PORTAL\PORTBG.C
call append PORTAL\PORTDRAW.C
call append PORTAL\MEMTEST.C
call append PORTAL\PORTCLIP.C
call append PORTAL\MERGE.C
call append PORTAL\PORTDATA.C
call append PORTAL\ORACLE.C
call append PORTAL\PERFCORE.C
call append PORTAL\PORTHW.C
call append PORTAL\PERFTEST.C
call append ACTREACT\AREDIT.H
call append ACTREACT\ARLOOP.H
call append ACTREACT\CONTAG8R.H
call append ACTREACT\CTACTBAS.H
call append ACTREACT\DUMBPROX.H
call append ACTREACT\MEDG8RID.H
call append ACTREACT\STIMUL8R.H
call append ACTREACT\STIMUL8_.H
call append ACTREACT\STIMULI.H
call append ACTREACT\STIMULI_.H
call append ACTREACT\STIMGUID.C
call append ACTREACT\STIMPROP.H
call append ACTREACT\STIMQFCT.H
call append ACTREACT\STIMSENS.H
call append ACTREACT\STIMSEN_.H
call append ACTREACT\STIMSRC.H
call append ACTREACT\STIMSRC_.H
call append ACTREACT\STIMTYPE.H
call append ACTREACT\RECEPTRO.H
call append ACTREACT\SENSBASE.H
call append ACTREACT\SENSTYPE.H
call append ACTREACT\SSRCBASE.H
call append ACTREACT\SSRCLIFE.H
call append ACTREACT\SSRCTYPE.H
call append ACTREACT\STIMBASE.H
call append ACTREACT\STIMGUID.H
call append ACTREACT\PROPAG8R.H
call append ACTREACT\PRPAG8N_.H
call append ACTREACT\PRPAG8R_.H
call append ACTREACT\RADIAG8R.H
call append ACTREACT\REACBASE.H
call append ACTREACT\REACTION.H
call append ACTREACT\REACTIO_.H
call append ACTREACT\REACTYPE.H
call append ACTREACT\MEDIAG8R.H
call append ACTREACT\PERIG8ID.H
call append ACTREACT\PERIOG8R.H
call append ACTREACT\PG8RBASE.H
call append ACTREACT\PG8RNULL.H
call append ACTREACT\PG8RTYPE.H
call append ACTREACT\PROPAG8N.H
call append AI\AI.H
call append AI\AIACTCST.H
call append AI\AIACTFOL.H
call append AI\AIACTFRB.H
call append AI\AIACTINV.H
call append AI\AIGROUND.H
call append AI\AIGUARD.H
call append AI\AIGUID.H
call append AI\AIGUNACT.H
call append AI\AIIDLE.H
call append AI\AIPRCORE.H
call append AI\AIPRDEV.H
call append AI\AIPROPS.H
call append AI\AIPROXY.H
call append AI\AIPRRNGD.H
call append AI\AIPRUTIL.H
call append AI\AIPATHDB.H
call append AI\AIPATROL.H
call append AI\AIPRABIL.H
call append AI\AIPRATTR.H
call append AI\AIPRCONV.H
call append AI\AINCBDMG.H
call append AI\AINET.H
call append AI\AINONCBT.H
call append AI\AINONHST.H
call append AI\AIOKBITS.H
call append AI\AIPATH.H
call append AI\AIMOVE.H
call append AI\AIMOVSUG.H
call append AI\AIMPLYR.H
call append AI\AIMTTEST.H
call append AI\AIMULTCB.H
call append AI\AIDEFEND.H
call append AI\AIDETECT.H
call append AI\AIDEV.H
call append AI\AIDFNDPT.H
call append AI\AIDIST.H
call append AI\AIDODGEP.H
call append AI\AIDOORMR.H
call append AI\AICTLSIG.H
call append AI\AIDBDRAW.H
call append AI\AIDBGCMP.H
call append AI\AIDEATH.H
call append AI\AIDEBUG.H
call append AI\AIRECOVR.H
call append AI\AIREPORT.H
call append AI\AIRNGWPN.H
call append AI\AISCHED.H
call append AI\AISCRABL.H
call append AI\AISCRM.H
call append AI\AISCRPT.H
call append AI\AISCRT.H
call append AI\AISGTCST.H
call append AI\AISIGNAL.H
call append AI\AISNDTYP.H
call append AI\AISNSDEV.H
call append AI\AISOUND.H
call append AI\AISTDMRG.H
call append AI\AITAGTYP.H
call append AI\AITEAMS.H
call append AI\AITEST.H
call append AI\AITHREAT.H
call append AI\AITRACE.H
call append AI\AITRGINF.H
call append AI\AITRIG.H
call append AI\AITURBS.H
call append AI\AITURRET.H
call append AI\AITYPE.H
call append AI\AIUTILS.H
call append AI\AIVISION.H
call append AI\AISTNAPI.H
call append AI\AISTUN.H
call append AI\AISUBABL.H
call append AI\AISUBCB.H
call append AI\AISUSLNK.H
call append AI\AISUSRSP.H
call append AI\AIWATCH.H
call append AI\AIWR.H
call append AI\AIWTCTYP.H
call append AI\AIPTHBAS.H
call append AI\AIPTHDBG.H
call append AI\AIPSDSCR.H
call append AI\AIPTHCST.H
call append AI\AIPTHEDG.H
call append AI\AIPTHFND.H
call append AI\AIPTHLOC.H
call append AI\AIPTHOBB.H
call append AI\AIPTHQRY.H
call append AI\AIPTHTYP.H
call append AI\AIPTHZON.H
call append AI\AIQDEATH.H
call append AI\AICBRNGD.H
call append AI\AICBRSHT.H
call append AI\AICBRSTL.H
call append AI\AICBRSTR.H
call append AI\AICBRTYP.H
call append AI\AICBRIDL.H
call append AI\AICBRLCT.H
call append AI\AICBRLOC.H
call append AI\AICBRMDS.H
call append AI\AICBRMOD.H
call append AI\AICBRMPR.H
call append AI\AICBRNEW.H
call append AI\AICAMERA.H
call append AI\AICBHTOH.H
call append AI\AICBLINK.H
call append AI\AICBRBKP.H
call append AI\AICBRCLO.H
call append AI\AICBRFLE.H
call append AI\AIBASCMP.H
call append AI\aibasctm.h
call append AI\AIBASMRG.H
call append AI\AIBASSNS.H
call append AI\AIBDYRSP.H
call append AI\AIAPICMP.H
call append AI\AIAPIIAI.H
call append AI\AIAPIDBQ.H
call append AI\AIAPIINF.H
call append AI\AIAPIMOV.H
call append AI\AIAPINET.H
call append AI\AIAPIPTH.H
call append AI\AIAPISND.H
call append AI\AIAPISNS.H
call append AI\AIAVOID.H
call append AI\AIAWARE.H
call append AI\AIBASABL.H
call append AI\AIBASACT.H
call append AI\AIBASATM.H
call append AI\AIBASATR.H
call append AI\AIBASBHV.H
call append AI\AIACTWT.H
call append AI\AIALERT.H
call append AI\AIALTRSP.H
call append AI\AIAPI.H
call append AI\AIAPIABL.H
call append AI\AIAPIACT.H
call append AI\AIAPIATR.H
call append AI\AIAPIBHV.H
call append AI\AIACTPS.H
call append AI\AIACTRNG.H
call append AI\AIACTSEQ.H
call append AI\AIACTSND.H
call append AI\AIACTTYP.H
call append AI\AIACTWND.H
call append AI\AIACTMOT.H
call append AI\AIACTMOV.H
call append AI\AIACTMRK.H
call append AI\AIACTORI.H
call append AI\AIACTPRX.H
call append AI\AIACTJR.H
call append AI\AIACTJS.H
call append AI\AIACTJSC.H
call append AI\AIACTLCH.H
call append AI\AIACTLOC.H
call append AI\AIFLEE.H
call append AI\AICBRVAN.H
call append AI\AICBRWND.H
call append AI\AICBTRSP.H
call append AI\AICDUMMY.H
call append AI\AICMDS.H
call append AI\AICNVABL.H
call append AI\AICNVAPI.H
call append AI\AICNVMAN.H
call append AI\AICNVRSE.H
call append AI\AICOMBAT.H
call append AI\AICPINIT.H
call append AI\AICRETSZ.H
call append AI\AIINFORM.H
call append AI\AIINVEST.H
call append AI\AIINVTYP.H
call append AI\AILISTEN.H
call append AI\AILOOP.H
call append AI\aiphycst.h
call append AI\AIMAN.H
call append AI\AIMANBHV.H
call append AI\AIE3BHV.H
call append AI\AIFOLLOW.H
call append AI\AIFREEZE.H
call append AI\AIGESTS.H
call append AI\AIGOAL.H
call append CSG\BSPDATA.C
call append CSG\BSPDATA.H
call append CSG\CSG.C
call append CSG\CSG.H
call append CSG\CSGALLOC.C
call append CSG\CSGALLOC.H
call append CSG\CSGBBOX.C
call append CSG\CSGBBOX.H
call append CSG\CSGBUILD.C
call append CSG\CSGCHECK.C
call append CSG\CSGCHECK.H
call append CSG\CSGCLIP.C
call append CSG\CSGCUBE.C
call append CSG\CSGDECAL.C
call append CSG\CSGEMIT.C
call append CSG\CSGFIND.C
call append CSG\CSGMEDIA.C
call append CSG\CSGMERGE.C
call append CSG\CSGMERGE.H
call append CSG\CSGUTIL.C
call append CSG\CSGUTIL.H
call append CSG\HEP.C
call append CSG\HEP.H
call append pch.cpp
call append RENDER\rendobj.cpp
call append SHOCK\Oshkgun.cpp
call append SHOCK\pshkgun.cpp
call append SIM\roomeax.cpp
call append SOUND\esndprop.cpp
call append SOUND\sndframe.cpp
call append DARK\drkchkcd.cpp
call append DARK\drkreprt.cpp
call append DARK\drkstats.cpp
call append DARK\drkfixpr.cpp
call append EDITOR\linkdraw.cpp
call append EDITOR\objedit.cpp
call append FRAMEWRK\buftagf.cpp
call append FRAMEWRK\ctag.cpp
call append FRAMEWRK\ctagset.cpp
call append FRAMEWRK\tagremap.cpp
call append MOTION\motdesc.cpp
call append OBJECT\objsys.cpp
call append AI\aidetect.cpp
call append AI\aiactps.cpp
call append AI\aipathdb.cpp
call append AI\aiphycst.cpp
call append FREZREAC.CPP
call append GIDPROP.CPP
call append INCTAB.CPP
call append KILLME.CPP
call append RENDER\ANTXLOOP.CPP
call append RENDER\TEXSAVE.CPP
call append RENDER\TEXTARCH.CPP
call append RENDER\WEATHER.CPP
call append RENDER\STAROBJ.CPP
call append RENDER\TANIMPRP.CPP
call append RENDER\SKYREND.CPP
call append RENDER\SLITPROP.CPP
call append RENDER\SPHRCST.CPP
call append RENDER\SPRKPROP.CPP
call append RENDER\SCRNMODE.CPP
call append RENDER\SCRNOVLS.CPP
call append RENDER\SKYOBJ.CPP
call append RENDER\RNDFLASH.CPP
call append RENDER\SCALPROP.CPP
call append RENDER\RENDER.CPP
call append RENDER\RENDPHYS.CPP
call append RENDER\RENDPROP.CPP
call append RENDER\PARTICLE.CPP
call append RENDER\PARTPROP.CPP
call append RENDER\PGRPPROP.CPP
call append RENDER\CAMOVL.CPP
call append RENDER\OBJTXTRP.CPP
call append RENDER\MNAMPROP.CPP
call append RENDER\MNUMPROP.CPP
call append RENDER\OBJCAST.CPP
call append RENDER\MESHTEX.CPP
call append RENDER\MISSREND.CPP
call append RENDER\CLOUDOBJ.CPP
call append RENDER\MESHATT.CPP
call append RENDER\HDSKPROP.CPP
call append RENDER\LITNET.CPP
call append RENDER\LITPROP.CPP
call append RENDER\GFXPROP.CPP
call append RENDER\H2OCOLOR.CPP
call append RENDER\OBJSHAPE.CPP
call append RENDER\FASPROP.CPP
call append RENDER\DISTOBJ.CPP
call append RENDER\DYNTEX.CPP
call append RENDER\ELITPROP.CPP
call append RENDER\FACE.CPP
call append RENDER\CORONA.CPP
call append RENDER\CELSTOBJ.CPP
call append RENDER\DISPLOOP.CPP
call append RENDER\ANTXSCPT.CPP
call append SCRIPT\ARSCRIPT.CPP
call append SCRIPT\ATKSCRPT.CPP
call append SCRIPT\BODSCRPT.CPP
call append SCRIPT\CAMSCRPT.CPP
call append SCRIPT\SCRPTST.CPP
call append SCRIPT\SNDSCRPT.CPP
call append SCRIPT\TWQSCRPT.CPP
call append SCRIPT\QUESSCPT.CPP
call append SCRIPT\ROOSCRPT.CPP
call append SCRIPT\SCRPTCMD.CPP
call append SCRIPT\SCRPTNET.CPP
call append SCRIPT\SCRPTPRP.CPP
call append SCRIPT\NETSCRPT.CPP
call append SCRIPT\OBJSCRPT.CPP
call append SCRIPT\PGRPSCPT.CPP
call append SCRIPT\PROPSCPT.CPP
call append SCRIPT\PUPSCRPT.CPP
call append SCRIPT\LINKSCPT.CPP
call append SCRIPT\LITSCRPT.CPP
call append SCRIPT\LOCKSCPT.CPP
call append SCRIPT\MISCRPRT.CPP
call append SCRIPT\MTSCRPT.CPP
call append SCRIPT\DATASCRS.CPP
call append SCRIPT\DMGSCRPT.CPP
call append SCRIPT\DRSCRPT.CPP
call append SCRIPT\ENGSCRPT.CPP
call append SCRIPT\KEYSCPT.CPP
call append SCRIPT\CDSCRIPT.CPP
call append SCRIPT\CONTSCRS.CPP
call append SHOCK\SHKABYSS.CPP
call append SHOCK\SHKAI.CPP
call append SHOCK\SHKAIABS.CPP
call append SHOCK\SHKAIBIT.CPP
call append SHOCK\SHKAICBR.CPP
call append SHOCK\SHK_BIND.CPP
call append SHOCK\TRANSMOD.CPP
call append SHOCK\SHKVHOT.CPP
call append SHOCK\SHKWEB.CPP
call append SHOCK\SHKWEPSC.CPP
call append SHOCK\SHKWSETT.CPP
call append SHOCK\SHKYORN.CPP
call append SHOCK\SHKTRPSI.CPP
call append SHOCK\SHKTTT.CPP
call append SHOCK\SHKUITUL.CPP
call append SHOCK\SHKUTILS.CPP
call append SHOCK\SHKVER.CPP
call append SHOCK\SHKTECHS.CPP
call append SHOCK\SHKTETR.CPP
call append SHOCK\SHKTLUCT.CPP
call append SHOCK\SHKTRAIN.CPP
call append SHOCK\SHKTRAIT.CPP
call append SHOCK\SHKSVBND.CPP
call append SHOCK\SHKSWINE.CPP
call append SHOCK\SHKSWMPR.CPP
call append SHOCK\SHKTCOMP.CPP
call append SHOCK\SHKTECH.CPP
call append SHOCK\SHKSOUND.CPP
call append SHOCK\SHKSTACK.CPP
call append SHOCK\SHKSTATS.CPP
call append SHOCK\SHKSTNRC.CPP
call append SHOCK\SHKSCOMP.CPP
call append SHOCK\SHKSCRPT.CPP
call append SHOCK\SHKSECUR.CPP
call append SHOCK\SHKSKILL.CPP
call append SHOCK\SHKSLOOP.CPP
call append SHOCK\SHKSNDPR.CPP
call append SHOCK\SHKRNDOV.CPP
call append SHOCK\SHKRNDST.CPP
call append SHOCK\SHKRSRCH.CPP
call append SHOCK\SHKSAVUI.CPP
call append SHOCK\SHKREACT.CPP
call append SHOCK\SHKREP.CPP
call append SHOCK\SHKREPRT.CPP
call append SHOCK\SHKRLOOP.CPP
call append SHOCK\SHKPSISC.CPP
call append SHOCK\SHKRACER.CPP
call append SHOCK\SHKRADAR.CPP
call append SHOCK\SHKRDROV.CPP
call append SHOCK\SHKPSI.CPP
call append SHOCK\SHKPSIIF.CPP
call append SHOCK\SHKPSIPR.CPP
call append SHOCK\SHKPSIPW.CPP
call append SHOCK\SHKPLPUP.CPP
call append SHOCK\SHKPRJPR.CPP
call append SHOCK\SHKPROJ.CPP
call append SHOCK\SHKPROP.CPP
call append SHOCK\SHKPSAMP.CPP
call append SHOCK\SHKPLAYR.CPP
call append SHOCK\SHKPLDMG.CPP
call append SHOCK\SHKPLGUN.CPP
call append SHOCK\SHKPLPSI.CPP
call append SHOCK\SHKPDOLL.CPP
call append SHOCK\SHKPICK.CPP
call append SHOCK\SHKPING.CPP
call append SHOCK\SHKOVRLD.CPP
call append SHOCK\SHKOVRLY.CPP
call append SHOCK\SHKOWRLD.CPP
call append SHOCK\SHKPARAM.CPP
call append SHOCK\SHKPATCH.CPP
call append SHOCK\SHKPDA.CPP
call append SHOCK\SHKNETAP.CPP
call append SHOCK\SHKNETUI.CPP
call append SHOCK\SHKOBJSC.CPP
call append SHOCK\SHKOPTMN.CPP
call append SHOCK\SHKMLOOK.CPP
call append SHOCK\SHKMMAX.CPP
call append SHOCK\SHKMULTI.CPP
call append SHOCK\SHKMUSIC.CPP
call append SHOCK\SHKNET.CPP
call append SHOCK\SHKMELPR.CPP
call append SHOCK\SHKMENU.CPP
call append SHOCK\SHKMETER.CPP
call append SHOCK\SHKMINIG.CPP
call append SHOCK\SHKLOOT.CPP
call append SHOCK\SHKMAIN.CPP
call append SHOCK\SHKMAP.CPP
call append SHOCK\SHKMELAB.CPP
call append SHOCK\SHKMELEE.CPP
call append SHOCK\SHKLBOX.CPP
call append SHOCK\SHKLDING.CPP
call append SHOCK\SHKLINKS.CPP
call append SHOCK\SHKLOOKO.CPP
call append SHOCK\SHKINIT.CPP
call append SHOCK\SHKINV.CPP
call append SHOCK\SHKINVPR.CPP
call append SHOCK\SHKKEY.CPP
call append SHOCK\SHKKEYPD.CPP
call append SHOCK\SHKLABEL.CPP
call append SHOCK\SHKHUD.CPP
call append SHOCK\SHKIFACE.CPP
call append SHOCK\SHKIFTUL.CPP
call append SHOCK\SHKHAZRD.CPP
call append SHOCK\SHKHCOMP.CPP
call append SHOCK\SHKHOGGA.CPP
call append SHOCK\SHKHOME.CPP
call append SHOCK\SHKHPLUG.CPP
call append SHOCK\SHKHRM.CPP
call append SHOCK\SHKGUN.CPP
call append SHOCK\SHKGUNMD.CPP
call append SHOCK\SHKGUNPR.CPP
call append SHOCK\SHKHACKS.CPP
call append SHOCK\SHKFROB.CPP
call append SHOCK\SHKFSYS.CPP
call append SHOCK\SHKGAME.CPP
call append SHOCK\SHKGANPR.CPP
call append SHOCK\SHKGOLF.CPP
call append SHOCK\SHKEDIT.CPP
call append SHOCK\SHKELEV.CPP
call append SHOCK\SHKEMAIL.CPP
call append SHOCK\SHKEXP.CPP
call append SHOCK\SHKFLASH.CPP
call append SHOCK\SHKDKYHG.CPP
call append SHOCK\SHKDLG.CPP
call append SHOCK\SHKDRPRP.CPP
call append SHOCK\SHKDMG.CPP
call append SHOCK\SHKDMPRP.CPP
call append SHOCK\SHKCS.CPP
call append SHOCK\SHKCTRL.CPP
call append SHOCK\SHKCYBER.CPP
call append SHOCK\SHKDEBRF.CPP
call append SHOCK\SHKCRMKY.CPP
call append SHOCK\SHKCROSS.CPP
call append SHOCK\SHKCROVR.CPP
call append SHOCK\SHKCRRUM.CPP
call append SHOCK\SHKCRSHO.CPP
call append SHOCK\SHKCRARM.CPP
call append SHOCK\SHKCRBAR.CPP
call append SHOCK\SHKCRDRD.CPP
call append SHOCK\SHKCRET.CPP
call append SHOCK\SHKCRHUM.CPP
call append SHOCK\SHKCMOBJ.CPP
call append SHOCK\SHKCOBPR.CPP
call append SHOCK\SHKCONT.CPP
call append SHOCK\SHKCRARA.CPP
call append SHOCK\SHKCAM.CPP
call append SHOCK\SHKCHARG.CPP
call append SHOCK\SHKCHAT.CPP
call append SHOCK\SHKCHECK.CPP
call append SHOCK\SHKCHKCD.CPP
call append SHOCK\SHKANMSP.CPP
call append SHOCK\SHKARMOR.CPP
call append SHOCK\SHKARMPR.CPP
call append SHOCK\SHKBACON.CPP
call append SHOCK\SHKBOOKO.CPP
call append SHOCK\SHKBLOOD.CPP
call append SHOCK\SHKAITRT.CPP
call append SHOCK\SHKAITSN.CPP
call append SHOCK\SHKAIUTL.CPP
call append SHOCK\SHKAIWND.CPP
call append SHOCK\SHKALARM.CPP
call append SHOCK\SHKAMMOV.CPP
call append SHOCK\SHKAISHO.CPP
call append SHOCK\SHKAISWA.CPP
call append SHOCK\SHKAISWM.CPP
call append SHOCK\SHKAITBS.CPP
call append SHOCK\SHKAITPR.CPP
call append SHOCK\SHKAIRCP.CPP
call append SHOCK\SHKAIREB.CPP
call append SHOCK\SHKAIRNB.CPP
call append SHOCK\SHKAISBS.CPP
call append SHOCK\SHKAISC.CPP
call append SHOCK\SHKAISHB.CPP
call append SHOCK\SHKAIPRB.CPP
call append SHOCK\SHKAIHCK.CPP
call append SHOCK\SHKAIPRO.CPP
call append SHOCK\SHKAIPTH.CPP
call append SHOCK\SHKAIRBS.CPP
call append SHOCK\SHKAIRCA.CPP
call append SHOCK\SHKAIMBS.CPP
call append SHOCK\SHKAIMC.CPP
call append SHOCK\SHKAIMUC.CPP
call append SHOCK\SHKAIPBS.CPP
call append SHOCK\SHKAIPR.CPP
call append SHOCK\SHKAIGNT.CPP
call append SHOCK\SHKAIGRA.CPP
call append SHOCK\SHKAIGRB.CPP
call append SHOCK\SHKAIJRA.CPP
call append SHOCK\SHKAIJSA.CPP
call append SHOCK\SHKAIDMR.CPP
call append SHOCK\SHKAIDTH.CPP
call append SHOCK\SHKAIEXP.CPP
call append SHOCK\SHKAIGBS.CPP
call append SHOCK\SHKAIGNA.CPP
call append SHOCK\SHKAICBS.CPP
call append SHOCK\SHKAICHA.CPP
call append SHOCK\SHKAICMD.CPP
call append SHOCK\SHKAICRB.CPP
call append SHOCK\SHKAIDBS.CPP
call append SIM\AVATAR.CPP
call append SIM\DOORPHYS.CPP
call append SIM\DOORREP.CPP
call append SIM\SIMTIME.CPP
call append SIM\WRBSP.CPP
call append SIM\ROOMCORE.CPP
call append SIM\WRLOOP.CPP
call append SIM\SIMMAN.CPP
call append SIM\ROOMS.CPP
call append SIM\ROOMUTIL.CPP
call append SIM\RPATHFND.CPP
call append SIM\RPATHS.CPP
call append SIM\RPORTAL.CPP
call append SIM\ROOM.CPP
call append SIM\DOORPROP.CPP
call append SIM\ROOMLOOP.CPP
call append SIM\ROOMPA.CPP
call append SIM\ROOMPROP.CPP
call append SIM\PLYRVMOT.CPP
call append SIM\PLYSKILL.CPP
call append SIM\PRJCTILE.CPP
call append SIM\PLYCBLLM.CPP
call append SIM\PLYRHDLR.CPP
call append SIM\PLYRLOOP.CPP
call append SIM\PLYRMODE.CPP
call append SIM\PLYRMOV.CPP
call append SIM\OBJPOS.CPP
call append SIM\OBJTOOL.CPP
call append SIM\PLAYTEST.CPP
call append SIM\PLYABLTY.CPP
call append SIM\OBJLOOP.CPP
call append SIM\OBJNET.CPP
call append SIM\GHOSTRCV.CPP
call append SIM\GHOSTSHK.CPP
call append SIM\GHOSTSND.CPP
call append SIM\GHOSTWEP.CPP
call append SIM\GHOSTLST.CPP
call append SIM\GHOSTLUP.CPP
call append SIM\GHOSTMSG.CPP
call append SIM\GHOSTPHY.CPP
call append SIM\FLOWARCH.CPP
call append SIM\GHOST.CPP
call append SIM\GHOSTHST.CPP
call append SOUND\AMBPROP.CPP
call append SOUND\APPSFX.CPP
call append SOUND\AUXSND.CPP
call append SOUND\SPCHREQ.CPP
call append SOUND\SPCHVOC.CPP
call append SOUND\SPEECH.CPP
call append SOUND\VOCORE.CPP
call append SOUND\SONGPLRI.CPP
call append SOUND\SONGUTIL.CPP
call append SOUND\SPCHDOM.CPP
call append SOUND\SPCHPROP.CPP
call append SOUND\SONGEDTR.CPP
call append SOUND\SONGFILE.CPP
call append SOUND\SONGI.CPP
call append SOUND\SONGID.CPP
call append SOUND\SONGMISS.CPP
call append SOUND\SNDGEN.CPP
call append SOUND\PSND.CPP
call append SOUND\SNDLOOP.CPP
call append SOUND\SNDNET.CPP
call append SOUND\SNDPROP.CPP
call append SOUND\SCHMSG.CPP
call append SOUND\SCHPROP.CPP
call append SOUND\SCHSAMPS.CPP
call append SOUND\PSNDINST.CPP
call append SOUND\SCHDB.CPP
call append SOUND\METASND.CPP
call append SOUND\SCHEMA.CPP
call append SOUND\SCHFILE.CPP
call append SOUND\ESND.CPP
call append SOUND\ESNDREAC.CPP
call append SOUND\PSNDAPI.CPP
call append UI\BUTTPANL.CPP
call append UI\JOYPOLL.CPP
call append UI\PANLTOOL.CPP
call append UI\UIAMOV.CPP
call append UI\UIANIM.CPP
call append UI\UIAPP.CPP
call append UI\MOVIE.CPP
call append UI\UIGAME.CPP
call append UI\UILOOP.CPP
call append UI\PANLMODE.CPP
call append DARK\BOWSCRPT.CPP
call append DARK\CCRAPPA.CPP
call append DARK\CCRBUG.CPP
call append DARK\CCRCRAY.CPP
call append DARK\CCRHUMAN.CPP
call append DARK\DRKLDOUT.CPP
call append DARK\DRKSAVE.CPP
call append DARK\DRKSAVUI.CPP
call append DARK\DRKSCRPT.CPP
call append DARK\DRKSCRS.CPP
call append DARK\DRKUIRES.CPP
call append DARK\DRKUISCR.CPP
call append DARK\DRKVO.CPP
call append DARK\DRK_BIND.CPP
call append DARK\DRKWBDY.CPP
call append DARK\DRKWBOW.CPP
call append DARK\DRKWSWD.CPP
call append DARK\DRKOPTMN.CPP
call append DARK\FILEPANL.CPP
call append DARK\GADSLIDE.CPP
call append DARK\DAICAM.CPP
call append DARK\DAIELEM.CPP
call append DARK\DAIFROG.CPP
call append DARK\DARKAI.CPP
call append DARK\DRKAMAP.CPP
call append DARK\DRKINVUI.CPP
call append DARK\DRKBOOK.CPP
call append DARK\DRKBRETH.CPP
call append DARK\DRKINVPR.CPP
call append DARK\DRKINVSC.CPP
call append DARK\DRKRUTIL.CPP
call append DARK\DRKSLOOP.CPP
call append DARK\DRKSOUND.CPP
call append DARK\DRKLINKS.CPP
call append DARK\DRKLOOT.CPP
call append DARK\DRKMENU.CPP
call append DARK\DRKMISLP.CPP
call append DARK\CRJOINT.CPP
call append DARK\CRROBOT.CPP
call append DARK\CRSMRBT.CPP
call append DARK\DRKDEBRF.CPP
call append DARK\DRKCMBAT.CPP
call append DARK\DRKCOLOR.CPP
call append DARK\DRKCRET.CPP
call append DARK\DRKDIFF.CPP
call append DARK\DRKGOALR.CPP
call append DARK\DRKMISS.CPP
call append DARK\DRKMSG.CPP
call append DARK\DRKNETAP.CPP
call append DARK\DRKPANL.CPP
call append DARK\DRKPLINV.CPP
call append DARK\DRKPWSCR.CPP
call append DARK\DRKPWUPS.CPP
call append DARK\DRKREACT.CPP
call append DARK\LOOTPROP.CPP
call append DARK\MESHPROP.CPP
call append DARK\METAGAME.CPP
call append DARK\PICK.CPP
call append DARK\PICKLOCK.CPP
call append DARK\PICKSCRS.CPP
call append DARK\PLYSCRPT.CPP
call append DARK\STATBAR.CPP
call append DARK\VISMETER.CPP
call append DARK\WEAPSCPT.CPP
call append DARK\DRKGAME.CPP
call append DEEPC\ACTREACT\DPCDRPRP.CPP
call append DEEPC\ACTREACT\DPCPROP.CPP
call append DEEPC\ACTREACT\DPCREACT.CPP
call append DEEPC\AI\DPCAI.CPP
call append DEEPC\AI\DPCAIABS.CPP
call append DEEPC\AI\DPCAIBIT.CPP
call append DEEPC\AI\DPCAICBR.CPP
call append DEEPC\AI\DPCAICBS.CPP
call append DEEPC\AI\DPCAIDMR.CPP
call append DEEPC\AI\DPCAIDTH.CPP
call append DEEPC\AI\DPCAIGNA.CPP
call append DEEPC\AI\DPCAIMBS.CPP
call append DEEPC\AI\DPCAIMUC.CPP
call append DEEPC\AI\DPCAIPBS.CPP
call append DEEPC\AI\DPCAIPR.CPP
call append DEEPC\AI\DPCAIPRO.CPP
call append DEEPC\AI\DPCAIPTH.CPP
call append DEEPC\AI\DPCAIRBS.CPP
call append DEEPC\AI\DPCAIRCP.CPP
call append DEEPC\AI\DPCAIREB.CPP
call append DEEPC\AI\DPCAIRNB.CPP
call append DEEPC\AI\DPCAISBS.CPP
call append DEEPC\AI\DPCAITBS.CPP
call append DEEPC\AI\DPCAIUTL.CPP
call append DEEPC\AI\DPCAIWND.CPP
call append DEEPC\AI\DPCSTNRC.CPP
call append DEEPC\AI\DPCAICHA.CPP
call append DEEPC\AI\DPCAICMD.CPP
call append DEEPC\AI\DPCAICRB.CPP
call append DEEPC\AI\DPCAIDGA.CPP
call append DEEPC\AI\DPCAIDGB.CPP
call append DEEPC\EDITOR\DPCEDIT.CPP
call append DEEPC\ENGFEAT\DPCFROB.CPP
call append DEEPC\ENGFEAT\DPCFSYS.CPP
call append DEEPC\GAME\DPCALARM.CPP
call append DEEPC\GAME\DPCBLOOD.CPP
call append DEEPC\GAME\DPCCHECK.CPP
call append DEEPC\GAME\DPCCHKCD.CPP
call append DEEPC\GAME\DPCCROSS.CPP
call append DEEPC\GAME\DPCGOALR.CPP
call append DEEPC\GAME\DPCHAZRD.CPP
call append DEEPC\GAME\DPCHCOMP.CPP
call append DEEPC\GAME\DPCHPLUG.CPP
call append DEEPC\GAME\DPCDMPRP.CPP
call append DEEPC\GAME\DPCELEV.CPP
call append DEEPC\GAME\DPCEMAIL.CPP
call append DEEPC\GAME\DPCGAME.CPP
call append DEEPC\GAME\DPCHRM.CPP
call append DEEPC\GAME\DPCINIT.CPP
call append DEEPC\GAME\DPCKEYPD.CPP
call append DEEPC\GAME\DPCLOOT.CPP
call append DEEPC\GAME\DPCMAIN.CPP
call append DEEPC\GAME\DPCPICK.CPP
call append DEEPC\GAME\DPCPLPUP.CPP
call append DEEPC\GAME\DPCREPRT.CPP
call append DEEPC\GAME\DPCSCOMP.CPP
call append DEEPC\GAME\DPCSECUR.CPP
call append DEEPC\GAME\DPCSLOOP.CPP
call append DEEPC\GAME\DPCMAP.CPP
call append DEEPC\GAME\DPCMISS.CPP
call append DEEPC\GAME\DPCMLOOK.CPP
call append DEEPC\GAME\DPCPATCH.CPP
call append DEEPC\GAME\DPCTLUCT.CPP
call append DEEPC\GAME\DPCVER.CPP
call append DEEPC\GAME\DPCWSETT.CPP
call append DEEPC\INPUT\DPCCTRL.CPP
call append DEEPC\INPUT\DPCKEY.CPP
call append DEEPC\INPUT\DPC_BIND.CPP
call append DEEPC\MOTION\DPCCRARA.CPP
call append DEEPC\MOTION\DPCCRARM.CPP
call append DEEPC\MOTION\DPCCRBAR.CPP
call append DEEPC\MOTION\DPCCRDRD.CPP
call append DEEPC\MOTION\DPCCRET.CPP
call append DEEPC\MOTION\DPCCRHUM.CPP
call append DEEPC\MOTION\DPCCRMKY.CPP
call append DEEPC\MOTION\DPCCROVR.CPP
call append DEEPC\MP\DPCNET.CPP
call append DEEPC\OBJECT\DPCARMPR.CPP
call append DEEPC\OBJECT\DPCDMG.CPP
call append DEEPC\OBJECT\DPCLINKS.CPP
call append DEEPC\PLAYER\DPCINV.CPP
call append DEEPC\PLAYER\DPCINVPR.CPP
call append DEEPC\PLAYER\DPCLOOKO.CPP
call append DEEPC\PLAYER\DPCMELAB.CPP
call append DEEPC\PLAYER\DPCMELEE.CPP
call append DEEPC\PLAYER\DPCPARAM.CPP
call append DEEPC\PLAYER\DPCPLAYR.CPP
call append DEEPC\PLAYER\DPCPLDMG.CPP
call append DEEPC\RENDER\DPCANMSP.CPP
call append DEEPC\RENDER\DPCCAM.CPP
call append DEEPC\RENDER\DPCCMOBJ.CPP
call append DEEPC\RENDER\DPCCOBPR.CPP
call append DEEPC\RENDER\DPCCS.CPP
call append DEEPC\RENDER\DPCRLOOP.CPP
call append DEEPC\RENDER\DPCRNDOV.CPP
call append DEEPC\RENDER\DPCUTILS.CPP
call append DEEPC\RENDER\DPCVHOT.CPP
call append DEEPC\SCRIPTS\DPCAISC.CPP
call append DEEPC\SCRIPTS\DPCHOME.CPP
call append DEEPC\SCRIPTS\DPCSCRPT.CPP
call append DEEPC\SCRIPTS\DPCSCRS.CPP
call append DEEPC\SCRIPTS\DPCWEPSC.CPP
call append DEEPC\SOUND\DPCSNDPR.CPP
call append DEEPC\SOUND\DPCSOUND.CPP
call append DEEPC\UI\DPCBOOKO.CPP
call append DEEPC\UI\DPCCHAT.CPP
call append DEEPC\UI\DPCCONT.CPP
call append DEEPC\UI\DPCDLG.CPP
call append DEEPC\UI\DPCHUD.CPP
call append DEEPC\UI\DPCIFACE.CPP
call append DEEPC\UI\DPCIFTUL.CPP
call append DEEPC\UI\DPCLBOX.CPP
call append DEEPC\UI\DPCLDING.CPP
call append DEEPC\UI\DPCMENU.CPP
call append DEEPC\UI\DPCMETER.CPP
call append DEEPC\UI\DPCMULTI.CPP
call append DEEPC\UI\DPCNETUI.CPP
call append DEEPC\UI\DPCOPTMN.CPP
call append DEEPC\UI\DPCOVRLY.CPP
call append DEEPC\UI\DPCPDA.CPP
call append DEEPC\UI\DPCSAVUI.CPP
call append DEEPC\UI\DPCSVBND.CPP
call append DEEPC\UI\DPCUITUL.CPP
call append DEEPC\UI\DPCYORN.CPP
call append DEEPC\WEAPON\DPCAMMOV.CPP
call append DEEPC\WEAPON\DPCFLASH.CPP
call append DEEPC\WEAPON\DPCGANPR.CPP
call append DEEPC\WEAPON\DPCGUN.CPP
call append DEEPC\WEAPON\DPCGUNPR.CPP
call append DEEPC\WEAPON\DPCMELPR.CPP
call append DEEPC\WEAPON\DPCPLGUN.CPP
call append DEEPC\WEAPON\DPCPRJPR.CPP
call append DEEPC\WEAPON\DPCPROJ.CPP
call append EDITOR\ARCMD.CPP
call append EDITOR\AUTOVBR.CPP
call append EDITOR\BROBJPRO.CPP
call append EDITOR\BRPROP.CPP
call append EDITOR\CONVPRED.CPP
call append EDITOR\DOORBLOK.CPP
call append EDITOR\EDITLINK.CPP
call append EDITOR\EDITPLST.CPP
call append EDITOR\FAMEDIT.CPP
call append EDITOR\FILEMENU.CPP
call append EDITOR\FLOWPNP.CPP
call append EDITOR\FVAREDIT.CPP
call append EDITOR\GED_CSG.CPP
call append EDITOR\GED_ROOM.CPP
call append EDITOR\ISDESCED.CPP
call append EDITOR\LINKEDIT.CPP
call append EDITOR\LNKTRAIT.CPP
call append EDITOR\MEDMENU.CPP
call append EDITOR\MEDPLAY.CPP
call append EDITOR\MENUS.CPP
call append EDITOR\MOTEDIT.CPP
call append EDITOR\OBJED.CPP
call append EDITOR\OBJHISTP.CPP
call append EDITOR\OTREEED.CPP
call append EDITOR\PHPROPED.CPP
call append EDITOR\PNPSLIDE.CPP
call append EDITOR\PROPED.CPP
call append EDITOR\PROPTEST.CPP
call append EDITOR\PSDIALOG.CPP
call append EDITOR\QUESEDIT.CPP
call append EDITOR\ROOMTOWR.CPP
call append EDITOR\SCRNEDIT.CPP
call append EDITOR\SCRPTED.CPP
call append EDITOR\SDESPARM.CPP
call append EDITOR\SIMPWRAP.CPP
call append EDITOR\STRPRPED.CPP
call append ENGFEAT\AUTOMAP.CPP
call append ENGFEAT\CAMPAIGN.CPP
call append ENGFEAT\CONTAIN.CPP
call append ENGFEAT\CONTPROP.CPP
call append ENGFEAT\DMGMODEL.CPP
call append ENGFEAT\DMGPROP.CPP
call append ENGFEAT\DMGREACT.CPP
call append ENGFEAT\ENGFEAT.CPP
call append ENGFEAT\FLINDER.CPP
call append ENGFEAT\FROBCTRL.CPP
call append ENGFEAT\FROBPROP.CPP
call append ENGFEAT\GUNFLASH.CPP
call append ENGFEAT\GUNPROP.CPP
call append ENGFEAT\HPPROP.CPP
call append ENGFEAT\INVLIMB.CPP
call append ENGFEAT\INVRNDPR.CPP
call append ENGFEAT\KEYSYS.CPP
call append ENGFEAT\LOCKPROP.CPP
call append ENGFEAT\OWNPROP.CPP
call append ENGFEAT\PICK.CPP
call append ENGFEAT\PRELDPRP.CPP
call append ENGFEAT\PROJLINK.CPP
call append ENGFEAT\PROJPROP.CPP
call append ENGFEAT\PROPREAC.CPP
call append ENGFEAT\QUESLOOP.CPP
call append ENGFEAT\QUESREAC.CPP
call append ENGFEAT\QUEST.CPP
call append ENGFEAT\QUESTPRP.CPP
call append ENGFEAT\SIMPDMG.CPP
call append ENGFEAT\SUSPROP.CPP
call append ENGFEAT\TRAPPROP.CPP
call append ENGFEAT\TWEQCTRL.CPP
call append ENGFEAT\TWEQPROP.CPP
call append ENGFEAT\TWEQREP.CPP
call append ENGFEAT\WEAPBOW.CPP
call append ENGFEAT\WEAPCB.CPP
call append ENGFEAT\WEAPHALO.CPP
call append ENGFEAT\WEAPHIT.CPP
call append ENGFEAT\WEAPON.CPP
call append ENGFEAT\WEAPPROP.CPP
call append ENGFEAT\WEAPREAC.CPP
call append ENGFEAT\X10GUISH.CPP
call append FRAMEWRK\BACKUP.CPP
call append FRAMEWRK\CDPLAYER.CPP
call append FRAMEWRK\CHAINEVT.CPP
call append FRAMEWRK\CTAGNET.CPP
call append FRAMEWRK\DAPPSINK.CPP
call append FRAMEWRK\GEN_BIND.CPP
call append FRAMEWRK\DISPATCH.CPP
call append FRAMEWRK\DXLOAD.CPP
call append FRAMEWRK\DXWRNDLG.CPP
call append FRAMEWRK\FCYTAGDB.CPP
call append FRAMEWRK\FILEVAR.CPP
call append FRAMEWRK\FLTANG.CPP
call append FRAMEWRK\GAMESCRN.CPP
call append FRAMEWRK\GAMESTR.CPP
call append FRAMEWRK\GAMETOOL.CPP
call append FRAMEWRK\HCHKTHRD.CPP
call append FRAMEWRK\IMGSRC.CPP
call append FRAMEWRK\INIT.CPP
call append FRAMEWRK\INITEDIT.CPP
call append FRAMEWRK\INITGAME.CPP
call append FRAMEWRK\LRESHASH.CPP
call append FRAMEWRK\LR_CACHE.CPP
call append FRAMEWRK\MAIN.CPP
call append FRAMEWRK\MISSBLAT.CPP
call append FRAMEWRK\MISSDIFF.CPP
call append FRAMEWRK\MISSTRIP.CPP
call append FRAMEWRK\NAMEMAP.CPP
call append FRAMEWRK\NETMAN.CPP
call append FRAMEWRK\NETMSG.CPP
call append FRAMEWRK\NETPROPS.CPP
call append FRAMEWRK\NETSIM.CPP
call append FRAMEWRK\NETSYNCH.CPP
call append FRAMEWRK\NETVOICE.CPP
call append FRAMEWRK\PICKGAME.CPP
call append FRAMEWRK\RAND.CPP
call append FRAMEWRK\REPORT.CPP
call append FRAMEWRK\REPRTHLP.CPP
call append FRAMEWRK\REPUTIL.CPP
call append FRAMEWRK\TAGDBDAT.CPP
call append FRAMEWRK\TAGDBIN.CPP
call append FRAMEWRK\TAGDBKEY.CPP
call append FRAMEWRK\TAGDBKST.CPP
call append FRAMEWRK\TAGDBOUT.CPP
call append FRAMEWRK\TAGPATCH.CPP
call append FRAMEWRK\SCRNDUMP.CPP
call append FRAMEWRK\DBFILE.CPP
call append FRAMEWRK\SUBSCRIP.CPP
call append MOTION\CEREBLLM.CPP
call append MOTION\CRATTACH.CPP
call append MOTION\CREATURE.CPP
call append MOTION\CRETPROP.CPP
call append MOTION\CREXP.CPP
call append MOTION\SKILLTAB.CPP
call append MOTION\MVRSNGLE.CPP
call append MOTION\MVRTPORT.CPP
call append MOTION\MVRUTILS.CPP
call append MOTION\PUPPET.CPP
call append MOTION\PUPPROP.CPP
call append MOTION\SKILLSET.CPP
call append MOTION\CRJOINT.CPP
call append MOTION\CRWPNAPI.CPP
call append MOTION\CRWPNLST.CPP
call append MOTION\CRWPNLUP.CPP
call append MOTION\MCOORD.CPP
call append MOTION\MOTDB.CPP
call append MOTION\MOTMNGR.CPP
call append MOTION\MOTPROP.CPP
call append MOTION\MOTSCHEM.CPP
call append MOTION\MOTSET.CPP
call append MOTION\MPUTIL.CPP
call append MOTION\MSCHUTIL.CPP
call append MOTION\MSKILSET.CPP
call append MOTION\MSKLTREE.CPP
call append MOTION\MVRCMBAT.CPP
call append MOTION\MVRFLAGS.CPP
call append MOTION\MVRFLBOW.CPP
call append MOTION\MVRGACT.CPP
call append MOTION\MVRGLIDE.CPP
call append MOTION\MVRGLOCO.CPP
call append MOTION\MVRPLYR.CPP
call append OBJECT\BINTRAIT.CPP
call append OBJECT\DATAOPS.CPP
call append OBJECT\TRAITQDB.CPP
call append OBJECT\TRCACHE.CPP
call append OBJECT\TRCACHUI.CPP
call append OBJECT\TRAITMAN.CPP
call append OBJECT\TRAITNUL.CPP
call append OBJECT\TRAITPRP.CPP
call append OBJECT\TRAITQ.CPP
call append OBJECT\STRPROP.CPP
call append OBJECT\TRAISRCH.CPP
call append OBJECT\TRAIT.CPP
call append OBJECT\TRAITLNK.CPP
call append OBJECT\RELATION.CPP
call append OBJECT\RELINVER.CPP
call append OBJECT\RELNULL.CPP
call append OBJECT\PROPSTOR.CPP
call append OBJECT\QUERYNUL.CPP
call append OBJECT\PROPNULL.CPP
call append OBJECT\PROPOBSV.CPP
call append OBJECT\PROPSAVE.CPP
call append OBJECT\PROPLINK.CPP
call append OBJECT\PROPLIST.CPP
call append OBJECT\PROPMAN.CPP
call append OBJECT\PROPMIX.CPP
call append OBJECT\PROPHASH.CPP
call append OBJECT\PROPIMP.CPP
call append OBJECT\PROPDB.CPP
call append OBJECT\PROPERTY.CPP
call append OBJECT\PROPFACE.CPP
call append OBJECT\PROPARRY.CPP
call append OBJECT\OSETLNKQ.CPP
call append OBJECT\PRCNITER.CPP
call append OBJECT\OBJPROXY.CPP
call append OBJECT\OBJQUERY.CPP
call append OBJECT\OBJREMAP.CPP
call append OBJECT\OBJLPARS.CPP
call append OBJECT\LNKBYOBJ.CPP
call append OBJECT\LNKQUERY.CPP
call append OBJECT\NAMEPROP.CPP
call append OBJECT\LINKQDB.CPP
call append OBJECT\LINKSET.CPP
call append OBJECT\LINKSTOR.CPP
call append OBJECT\LINKLOOP.CPP
call append OBJECT\LINKMAN.CPP
call append OBJECT\LINKPROP.CPP
call append OBJECT\LINKBOTH.CPP
call append OBJECT\LINKDATA.CPP
call append OBJECT\LINKDB.CPP
call append OBJECT\LINK.CPP
call append OBJECT\LINKARRY.CPP
call append OBJECT\DONORQ.CPP
call append OBJECT\EDITTOOL.CPP
call append PHYSICS\COLLIDE.CPP
call append PHYSICS\COLLPROP.CPP
call append PHYSICS\GUNPROJ.CPP
call append PHYSICS\GUNVHOT.CPP
call append PHYSICS\OBJMEDIA.CPP
call append PHYSICS\SPHERCHK.CPP
call append PHYSICS\PHMOD.CPP
call append PHYSICS\PHUTILS.CPP
call append PHYSICS\PHYSAPI.CPP
call append PHYSICS\PHYSCAST.CPP
call append PHYSICS\PHYSLOOP.CPP
call append PHYSICS\PHYSTEST.CPP
call append PHYSICS\PHSCRPT.CPP
call append PHYSICS\PHSUBMOD.CPP
call append PHYSICS\PHTERR.CPP
call append PHYSICS\PHTXTPRP.CPP
call append PHYSICS\PHPPSCPT.CPP
call append PHYSICS\PHPROPS.CPP
call append PHYSICS\PHREF.CPP
call append PHYSICS\PHREPORT.CPP
call append PHYSICS\PHMSG.CPP
call append PHYSICS\PHMTERR.CPP
call append PHYSICS\PHMTPROP.CPP
call append PHYSICS\PHMTSCPT.CPP
call append PHYSICS\PHNET.CPP
call append PHYSICS\PHOPROP.CPP
call append PHYSICS\PHMODOBB.CPP
call append PHYSICS\PHMODS.CPP
call append PHYSICS\PHMODSPH.CPP
call append PHYSICS\PHMODUTL.CPP
call append PHYSICS\PHMOTION.CPP
call append PHYSICS\PHMEDTR.CPP
call append PHYSICS\PHMOAPI.CPP
call append PHYSICS\PHPROP.CPP
call append PHYSICS\PHMODBSP.CPP
call append PHYSICS\PHCTRL.CPP
call append PHYSICS\PHDYN.CPP
call append PHYSICS\PHFLIST.CPP
call append PHYSICS\PHLISTEN.CPP
call append PHYSICS\PHCORE.CPP
call append PHYSICS\PHCLIMB.CPP
call append PHYSICS\PHCLSN.CPP
call append PHYSICS\PHCONTCT.CPP
call append ACTREACT\ARLOOP.CPP
call append ACTREACT\CONTAG8R.CPP
call append ACTREACT\DUMBPROX.CPP
call append ACTREACT\MEDIAG8R.CPP
call append ACTREACT\STIMULI.CPP
call append ACTREACT\RADIAG8R.CPP
call append ACTREACT\STIMSENS.CPP
call append ACTREACT\STIMSRC.CPP
call append ACTREACT\STIMUL8R.CPP
call append ACTREACT\SSRCLIFE.CPP
call append ACTREACT\STIMBASE.CPP
call append ACTREACT\PROPAG8R.CPP
call append ACTREACT\REACTION.CPP
call append ACTREACT\PERIOG8R.CPP
call append ACTREACT\PG8RNULL.CPP
call append ACTREACT\PROPAG8N.CPP
call append AI\AI.CPP
call append AI\AIACTCST.CPP
call append AI\AIACTFOL.CPP
call append AI\AIACTFRB.CPP
call append AI\AIACTINV.CPP
call append AI\AIGROUND.CPP
call append AI\AIGUARD.CPP
call append AI\AIGUNACT.CPP
call append AI\AIIDLE.CPP
call append AI\AIINFORM.CPP
call append AI\AIPRDEV.CPP
call append AI\AIPROXY.CPP
call append AI\AIPROPS.CPP
call append AI\AIPRRNGD.CPP
call append AI\AIPRUTIL.CPP
call append AI\AIUTILS.CPP
call append AI\AIPATROL.CPP
call append AI\AIPRABIL.CPP
call append AI\AIPRATTR.CPP
call append AI\AIPRCONV.CPP
call append AI\AIPRCORE.CPP
call append AI\AIPTHCST.CPP
call append AI\AINET.CPP
call append AI\AINETMAN.CPP
call append AI\AINONCBT.CPP
call append AI\AIPATH.CPP
call append AI\AIMOVMOT.CPP
call append AI\AIMOVSUG.CPP
call append AI\AIMPLYR.CPP
call append AI\AIMTTEST.CPP
call append AI\AINCBDMG.CPP
call append AI\AIMULTCB.CPP
call append AI\AIPTHFND.CPP
call append AI\AIACTLOC.CPP
call append AI\AIDEV.CPP
call append AI\AIDODGEP.CPP
call append AI\AIDOORMR.CPP
call append AI\AIFLEE.CPP
call append AI\AIDBDRAW.CPP
call append AI\AIDBGCMP.CPP
call append AI\AIDEATH.CPP
call append AI\AIDEBUG.CPP
call append AI\AIDEFEND.CPP
call append AI\AIFOLLOW.CPP
call append AI\AIREPORT.CPP
call append AI\AISCRABL.CPP
call append AI\AISCRPT.CPP
call append AI\AISGTCST.CPP
call append AI\AISOUND.CPP
call append AI\AISNSDEV.CPP
call append AI\AISTDMRG.CPP
call append AI\AITAGTYP.CPP
call append AI\AITEAMS.CPP
call append AI\AITEST.CPP
call append AI\AITHREAT.CPP
call append AI\AITRIG.CPP
call append AI\AITURBS.CPP
call append AI\AITURRET.CPP
call append AI\AIWATCH.CPP
call append AI\AIACTJR.CPP
call append AI\AISTUN.CPP
call append AI\AISUBABL.CPP
call append AI\AISUBCB.CPP
call append AI\AISUSLNK.CPP
call append AI\AISUSRSP.CPP
call append AI\AIWR.CPP
call append AI\AIPTHDBG.CPP
call append AI\AIMAN.CPP
call append AI\AICBRNEW.CPP
call append AI\AICBRSHT.CPP
call append AI\AIPTHLOC.CPP
call append AI\AIACTJS.CPP
call append AI\AIPTHEDG.CPP
call append AI\AIPTHOBB.CPP
call append AI\AIPTHZON.CPP
call append AI\AIQDEATH.CPP
call append AI\AIRECOVR.CPP
call append AI\AICBRNGD.CPP
call append AI\AIACTJSC.CPP
call append AI\AICAMERA.CPP
call append AI\AICBRSTL.CPP
call append AI\AICBRSTR.CPP
call append AI\AICBRVAN.CPP
call append AI\AICBRLOC.CPP
call append AI\AICBRMOD.CPP
call append AI\AICBRMPR.CPP
call append AI\AIACTLCH.CPP
call append AI\AICBHTOH.CPP
call append AI\AICMDS.CPP
call append AI\AICBRBKP.CPP
call append AI\AICBRCLO.CPP
call append AI\AICBRFLE.CPP
call append AI\AICBRIDL.CPP
call append AI\AIBASCTM.CPP
call append AI\AIBASSNS.CPP
call append AI\AIBASMRG.CPP
call append AI\AIBDYRSP.CPP
call append AI\AICRETSZ.CPP
call append AI\AIAVOID.CPP
call append AI\AIAWARE.CPP
call append AI\AIBASABL.CPP
call append AI\AIBASACT.CPP
call append AI\AIBASATM.CPP
call append AI\AIBASBHV.CPP
call append AI\AIACTWT.CPP
call append AI\AIALTRSP.CPP
call append AI\AIACTMOT.CPP
call append AI\AIACTRNG.CPP
call append AI\AIACTSEQ.CPP
call append AI\AIACTSND.CPP
call append AI\AIACTWND.CPP
call append AI\AIACTMOV.CPP
call append AI\AIACTMRK.CPP
call append AI\AIACTNET.CPP
call append AI\AIACTORI.CPP
call append AI\AIACTPRX.CPP
call append AI\AICDUMMY.CPP
call append AI\AICNVABL.CPP
call append AI\AICOMBAT.CPP
call append AI\AIINVEST.CPP
call append AI\AICBRWND.CPP
call append AI\AICBTRSP.CPP
call append AI\AIMOVE.CPP
call append AI\AICNVMAN.CPP
call append AI\AICNVRSE.CPP
call append AI\AICPINIT.CPP
call append AI\AILISTEN.CPP
call append AI\AIE3BHV.CPP
call append AI\AIFREEZE.CPP
call append AI\AIGOAL.CPP
