#pragma once
DEFINE_LG_GUID(IID_IBaseGunDescProperty, 0xd5);
DEFINE_LG_GUID(IID_IGunStateProperty, 0xf9);
DEFINE_LG_GUID(IID_IAIGunDescProperty, 0x16f);
DEFINE_LG_GUID(IID_IPlayerGunDescProperty, 0x16e);
DEFINE_LG_GUID(IID_IGunAnimProperty, 0x17c);
DEFINE_LG_GUID(IID_IGunReliabilityProperty, 0x1b3);
DEFINE_LG_GUID(IID_IGunKickProperty, 0x1b7);
DEFINE_LG_GUID(IID_IProjectileProperty, 0x190);
DEFINE_LG_GUID(IID_ICannisterProperty, 0xdc);
